/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface DeleteEntityTransferPathParams {
    /**
     * @description The UUID of the Entity Transfer.
     * @type string, uuid
    */
    token: string;
}

/**
 * @description Entity Transfer canceled.
*/
export type DeleteEntityTransfer200 = object;

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface DeleteEntityTransferError {
    /**
     * @type array
    */
    errors: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string
        */
        field: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string
        */
        reason: string;
    }[];
}

export type DeleteEntityTransferMutationResponse = DeleteEntityTransfer200;

export type DeleteEntityTransferMutation = {
    Response: DeleteEntityTransfer200;
    PathParams: DeleteEntityTransferPathParams;
    Errors: any;
};