/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface DeleteVlanPathParams {
    /**
     * @description The label of the VLAN to be deleted.
     * @type string
    */
    label: string;
    /**
     * @description The VLAN\'s region.
     * @type string
    */
    regionId: string;
}

/**
 * @description The VLAN was deleted.
*/
export type DeleteVlan200 = object;

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface DeleteVlanError {
    /**
     * @type array
    */
    errors: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string
        */
        field: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string
        */
        reason: string;
    }[];
}

export type DeleteVlanMutationResponse = DeleteVlan200;

export type DeleteVlanMutation = {
    Response: DeleteVlan200;
    PathParams: DeleteVlanPathParams;
    Errors: any;
};