/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const getAccountSettings200InterfacesForNewLinodesEnum = {
    "legacy_config_only": "legacy_config_only",
    "legacy_config_default_but_linode_allowed": "legacy_config_default_but_linode_allowed",
    "linode_default_but_legacy_config_allowed": "linode_default_but_legacy_config_allowed",
    "linode_only": "linode_only"
} as const;

export type GetAccountSettings200InterfacesForNewLinodesEnumKey = (typeof getAccountSettings200InterfacesForNewLinodesEnum)[keyof typeof getAccountSettings200InterfacesForNewLinodesEnum];

export const getAccountSettings200MaintenancePolicyEnum = {
    "linode/migrate": "linode/migrate",
    "linode/power_off_on": "linode/power_off_on"
} as const;

export type GetAccountSettings200MaintenancePolicyEnumKey = (typeof getAccountSettings200MaintenancePolicyEnum)[keyof typeof getAccountSettings200MaintenancePolicyEnum];

export const getAccountSettings200ObjectStorageEnum = {
    "disabled": "disabled",
    "suspended": "suspended",
    "active": "active"
} as const;

export type GetAccountSettings200ObjectStorageEnumKey = (typeof getAccountSettings200ObjectStorageEnum)[keyof typeof getAccountSettings200ObjectStorageEnum];

/**
 * @description Returns a single Account settings object.
*/
export interface GetAccountSettings200 {
    /**
     * @description Account-wide backups default.  If `true`, all Linodes created will automatically be enrolled in the Backups service.  If `false`, Linodes will not be enrolled by default, but may still be enrolled on creation or later.
     * @type boolean
    */
    backups_enabled: boolean;
    /**
     * @description __Beta__ Defines if new Linodes can use legacy configuration interfaces:\n- `legacy_config_only`. All new Linodes need to use legacy configuration interfaces. Prevously created Linodes with Linode Interfaces can still exist. Linodes using legacy configuration interfaces can\'t be upgraded to use Linode Interfaces.\n- `legacy_config_default_but_linode_allowed`. New Linodes can use legacy configuration interfaces or Linode Interfaces, depending on the `interface_generation` setting specified when creating the Linode. By default, new Linodes use legacy configuration interfaces unless otherwise specified. Linodes that use legacy configuration interfaces can upgrade to Linode Interfaces. This is the default setting for existing accounts.\n- `linode_default_but_legacy_config_allowed`. New Linodes can use legacy configuration interfaces or Linode Interfaces, depending on the `interface_generation` setting specified when creating the Linode. By default, new Linodes use Linode Interfaces unless otherwise specified. Linodes that use legacy configuration interfaces can upgrade to Linode interfaces. This is the default setting for new accounts.\n- `linode_only`. All new Linodes need to use Linode Interfaces. Prevously created Linodes with legacy configuration profile interfaces can still exist if they were created under a previous setting. Linodes using legacy configuration interfaces can be upgraded to Linode Interfaces.
     * @type string
    */
    interfaces_for_new_linodes: GetAccountSettings200InterfacesForNewLinodesEnumKey;
    /**
     * @description __Read-only__ The Longview Pro tier you are currently subscribed to. The value must be a [Longview subscription](https://techdocs.akamai.com/linode-api/reference/get-longview-subscriptions) ID or `null` for Longview Free.
     * @type string
    */
    readonly longview_subscription: string;
    /**
     * @description __Beta__ Defines the default maintenance policy for new Linodes created on this account. Review [maintenance policy](https://techdocs.akamai.com/cloud-computing/docs/host-maintenance-policy) documentation for more details.
     * @type string
    */
    maintenance_policy: GetAccountSettings200MaintenancePolicyEnumKey;
    /**
     * @description __Read-only__ Our 24/7 incident response service. This robust, multi-homed monitoring system distributes monitoring checks to ensure that your servers remain online and available at all times. Linode Managed can monitor any service or software stack reachable over TCP or HTTP. Once you add a service to Linode Managed, we\'ll monitor it for connectivity, response, and total request time.
     * @type boolean
    */
    readonly managed: boolean;
    /**
     * @description Enables network helper across all users by default for new Linodes and Linode Configs.
     * @type boolean
    */
    network_helper: boolean;
    /**
     * @description __Read-only__ A string describing the status of this account\'s Object Storage service enrollment.
     * @default "disabled"
     * @type string
    */
    readonly object_storage: GetAccountSettings200ObjectStorageEnumKey;
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface GetAccountSettingsError {
    /**
     * @type array
    */
    errors: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string
        */
        field: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string
        */
        reason: string;
    }[];
}

export type GetAccountSettingsQueryResponse = GetAccountSettings200;

export type GetAccountSettingsQuery = {
    Response: GetAccountSettings200;
    Errors: any;
};