/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface GetClientsQueryParams {
    /**
     * @description The page of a collection to return.
     * @minLength 1
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items to return per page.
     * @minLength 25
     * @maxLength 500
     * @default 100
     * @type integer | undefined
    */
    page_size?: number;
}

export const dataStatusEnum11 = {
    "active": "active",
    "disabled": "disabled",
    "suspended": "suspended"
} as const;

export type DataStatusEnum11Key = (typeof dataStatusEnum11)[keyof typeof dataStatusEnum11];

/**
 * @description A paginated list of OAuth Clients.
*/
export interface GetClients200 {
    /**
     * @type array
    */
    data: {
        /**
         * @description __Read-only__ The OAuth Client ID.  This is used to identify the client, and is a publicly known value (it is not a secret).
         * @type string
        */
        readonly id: string;
        /**
         * @description __Filterable__ The name of this application.  This will be presented to users when they are asked to grant it access to their Account.
         * @minLength 1
         * @maxLength 512
         * @type string
        */
        label: string;
        /**
         * @description __Filterable__ If this is a public or private OAuth Client.  Public clients have a slightly different authentication workflow than private clients.  See the [OAuth spec](https://oauth.net/2/) for more details.
         * @default false
         * @type boolean
        */
        public: boolean;
        /**
         * @description The location a successful log in from [login.linode.com](https://login.linode.com) should be redirected to for this client.  The receiver of this redirect should be ready to accept an OAuth exchange code and finish the OAuth exchange.
         * @type string, url
        */
        redirect_uri: string;
        /**
         * @description __Read-only__ The OAuth Client secret, used in the OAuth exchange.  This is returned as `<REDACTED>` except when an OAuth Client is created or its secret is reset.  This is a secret, and should not be shared or disclosed publicly.
         * @type string
        */
        readonly secret: string;
        /**
         * @description __Read-only__ The status of this application.  `active` by default.
         * @type string
        */
        readonly status: DataStatusEnum11Key;
        /**
         * @description __Read-only__ The URL where this client\'s thumbnail may be viewed, or `null` if this client does not have a thumbnail set.
         * @type string, url
        */
        readonly thumbnail_url: string | null;
    }[];
    /**
     * @description __Read-only__ The current [page](https://techdocs.akamai.com/linode-api/reference/pagination).
     * @type integer
    */
    readonly page: number;
    /**
     * @description __Read-only__ The total number of [pages](https://techdocs.akamai.com/linode-api/reference/pagination).
     * @type integer
    */
    readonly pages: number;
    /**
     * @description __Read-only__ The total number of results.
     * @type integer
    */
    readonly results: number;
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface GetClientsError {
    /**
     * @type array
    */
    errors: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string
        */
        field: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string
        */
        reason: string;
    }[];
}

export type GetClientsQueryResponse = GetClients200;

export type GetClientsQuery = {
    Response: GetClients200;
    QueryParams: GetClientsQueryParams;
    Errors: any;
};