/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface GetDatabasesTypesQueryParams {
    /**
     * @description The page of a collection to return.
     * @minLength 1
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items to return per page.
     * @minLength 25
     * @maxLength 500
     * @default 100
     * @type integer | undefined
    */
    page_size?: number;
}

export const dataClassEnum = {
    "dedicated": "dedicated",
    "shared": "shared",
    "premium": "premium"
} as const;

export type DataClassEnumKey = (typeof dataClassEnum)[keyof typeof dataClassEnum];

export const mysqlQuantityEnum = {
    "1": 1,
    "2": 2,
    "3": 3
} as const;

export type MysqlQuantityEnumKey = (typeof mysqlQuantityEnum)[keyof typeof mysqlQuantityEnum];

export const postgresqlQuantityEnum = {
    "1": 1,
    "2": 2,
    "3": 3
} as const;

export type PostgresqlQuantityEnumKey = (typeof postgresqlQuantityEnum)[keyof typeof postgresqlQuantityEnum];

/**
 * @description Returns a paginated list of all Managed Databases types.
*/
export interface GetDatabasesTypes200 {
    /**
     * @description __Read-only__ The current [page](https://techdocs.akamai.com/linode-api/reference/pagination).
     * @type integer
    */
    readonly page: number;
    /**
     * @description __Read-only__ The total number of [pages](https://techdocs.akamai.com/linode-api/reference/pagination).
     * @type integer
    */
    readonly pages: number;
    /**
     * @description __Read-only__ The total number of results.
     * @type integer
    */
    readonly results: number;
    /**
     * @type array
    */
    data: {
        /**
         * @description The Linode class category. This can be [dedicated](https://techdocs.akamai.com/cloud-computing/docs/dedicated-cpu-compute-instances), [shared](https://techdocs.akamai.com/cloud-computing/docs/shared-cpu-compute-instances), or [premium](https://techdocs.akamai.com/cloud-computing/docs/premium-compute-instances).\n\n> 📘\n>\n> Premium plan Linodes are available in limited regions.
         * @type string
        */
        class: DataClassEnumKey;
        /**
         * @description The amount of disk space set aside for Databases of this plan type. The value is represented in megabytes.
         * @type integer
        */
        disk: number;
        /**
         * @description Information for the supported third-party databases that can be used with Managed Databases.
         * @type object
        */
        engines: {
            /**
             * @description Pricing details for MySQL Managed Databases.
             * @type array
            */
            mysql: {
                /**
                 * @description Cost in US dollars, broken down into hourly and monthly charges.
                 * @type object
                */
                price: {
                    /**
                     * @description Cost (in US dollars) per hour for this subscription tier.
                     * @type number
                    */
                    hourly: number;
                    /**
                     * @description Maximum cost (in US dollars) per month for this subscription tier.
                     * @type number
                    */
                    monthly: number;
                };
                /**
                 * @description The number of nodes for the Managed Database cluster for this subscription tier.
                 * @type integer
                */
                quantity: MysqlQuantityEnumKey;
            }[];
            /**
             * @description Pricing details for PostgreSQL Managed Databases.
             * @type array
            */
            postgresql: {
                /**
                 * @description Cost in US dollars, broken down into hourly and monthly charges.
                 * @type object
                */
                price: {
                    /**
                     * @description Cost (in US dollars) per hour for this subscription tier.
                     * @type number
                    */
                    hourly: number;
                    /**
                     * @description Maximum cost (in US dollars) per month for this subscription tier.
                     * @type number
                    */
                    monthly: number;
                };
                /**
                 * @description The number of nodes for the Managed Database cluster for this subscription tier.
                 * @type integer
                */
                quantity: PostgresqlQuantityEnumKey;
            }[];
        };
        /**
         * @description __Read-only__ The ID representing the Managed Database node plan type.
         * @type string
        */
        readonly id: string;
        /**
         * @description __Read-only__ A human-readable string that describes each plan type. For display purposes only.
         * @type string
        */
        readonly label: string;
        /**
         * @description The amount of RAM allocated to Database created of this plan type. The value is represented in megabytes.
         * @type integer
        */
        memory: number;
        /**
         * @description The number of CPUs allocated to databases of this plan type.
         * @type integer
        */
        vcpus: number;
    }[];
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface GetDatabasesTypesError {
    /**
     * @type array
    */
    errors: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string
        */
        field: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string
        */
        reason: string;
    }[];
}

export type GetDatabasesTypesQueryResponse = GetDatabasesTypes200;

export type GetDatabasesTypesQuery = {
    Response: GetDatabasesTypes200;
    QueryParams: GetDatabasesTypesQueryParams;
    Errors: any;
};