/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface GetDashboardsPathParams {
    /**
     * @description The Akamai Cloud Computing service being monitored. To see your currently supported services, run the [List supported service types](https://techdocs.akamai.com/linode-api/reference/get-monitor-services) operation and store the appropriate `service_type`.
     * @type string
    */
    serviceType: string;
}

export const dataTypeEnum20 = {
    "standard": "standard"
} as const;

export type DataTypeEnum20Key = (typeof dataTypeEnum20)[keyof typeof dataTypeEnum20];

export const widgetsAggregateFunctionEnum3 = {
    "min": "min",
    "max": "max",
    "avg": "avg",
    "sum": "sum",
    "rate": "rate",
    "increase": "increase"
} as const;

export type WidgetsAggregateFunctionEnum3Key = (typeof widgetsAggregateFunctionEnum3)[keyof typeof widgetsAggregateFunctionEnum3];

export const widgetsChartTypeEnum3 = {
    "line": "line",
    "area": "area"
} as const;

export type WidgetsChartTypeEnum3Key = (typeof widgetsChartTypeEnum3)[keyof typeof widgetsChartTypeEnum3];

export const widgetsSizeEnum3 = {
    "6": "6",
    "12": "12"
} as const;

export type WidgetsSizeEnum3Key = (typeof widgetsSizeEnum3)[keyof typeof widgetsSizeEnum3];

export const widgetsUnitEnum3 = {
    "%": "%",
    "Bytes": "Bytes",
    "sec": "sec",
    "bps": "bps",
    "msec": "msec",
    "Bps": "Bps",
    "KB": "KB",
    "MB": "MB",
    "GB": "GB",
    "rate": "rate",
    "percentile": "percentile",
    "ratio": "ratio",
    "OPS": "OPS",
    "IOPS": "IOPS"
} as const;

export type WidgetsUnitEnum3Key = (typeof widgetsUnitEnum3)[keyof typeof widgetsUnitEnum3];

/**
 * @description Returns a paginated list of dashboards.
*/
export interface GetDashboards200 {
    /**
     * @type array
    */
    data: {
        /**
         * @description When the dashboard was created.
         * @type string, date-time
        */
        created: string;
        /**
         * @description The unique ID assigned to the dashboard.
         * @type integer
        */
        id: number;
        /**
         * @description The name of the dashboard. This is used for display purposes in Akamai Cloud Manager.
         * @type string
        */
        label: string;
        /**
         * @description The Akamai Cloud Computing service used by this dashboard.
         * @type string
        */
        service_type: string;
        /**
         * @description The type of dashboard. Currently, this can only be `standard` for a dashboard, which uses default formatting.
         * @type string
        */
        type: DataTypeEnum20Key;
        /**
         * @description When the dashboard was last updated.
         * @type string, date-time
        */
        updated: string;
        /**
         * @description The widgets used in the dashboard.
         * @type array
        */
        widgets: {
            /**
             * @description The aggregate function for the metric. This defaults to `avg` for average.
             * @default "avg"
             * @type string
            */
            aggregate_function: WidgetsAggregateFunctionEnum3Key;
            /**
             * @description The type of chart used in the widget. This can be `line` for a line chart or `area` for an area chart.
             * @type string
            */
            chart_type: WidgetsChartTypeEnum3Key;
            /**
             * @description The color used in the widget.
             * @type string
            */
            color: string;
            /**
             * @description The name of the widget. This is used for display purposes in Akamai Cloud Manager.
             * @type string
            */
            label: string;
            /**
             * @description The metric used in the widget.
             * @type string
            */
            metric: string;
            /**
             * @description The size of the widget. This can be `6` or `12` grid units, expressed as strings.
             * @type string
            */
            size: WidgetsSizeEnum3Key;
            /**
             * @description The unit of the metric. This can be values like `%` for percentage or `GB` for gigabyte.
             * @type string
            */
            unit: WidgetsUnitEnum3Key;
            /**
             * @description The label for the y-axis in the widget\'s chart.
             * @type string
            */
            y_label: string;
        }[];
    }[];
    /**
     * @description __Read-only__ The current [page](https://techdocs.akamai.com/linode-api/reference/pagination).
     * @type integer
    */
    readonly page: number;
    /**
     * @description __Read-only__ The total number of [pages](https://techdocs.akamai.com/linode-api/reference/pagination).
     * @type integer
    */
    readonly pages: number;
    /**
     * @description __Read-only__ The total number of results.
     * @type integer
    */
    readonly results: number;
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface GetDashboardsError {
    /**
     * @type array
    */
    errors: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string
        */
        field: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string
        */
        reason: string;
    }[];
}

export type GetDashboardsQueryResponse = GetDashboards200;

export type GetDashboardsQuery = {
    Response: GetDashboards200;
    PathParams: GetDashboardsPathParams;
    Errors: any;
};