/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface GetImagesSharegroupsImagePathParams {
    /**
     * @description Slug identifier assigned to the private image upon creation. This identifier includes a slash (`/`), which must be URL-encoded in requests to prevent breaking the URL structure.
     * @type string
    */
    imageId: string;
}

/**
 * @description Returns a paginated list of share groups.
*/
export interface GetImagesSharegroupsImage200 {
    /**
     * @type array
    */
    data: {
        /**
         * @description __Read-only__ When this share group was created.
         * @type string, date-time
        */
        readonly created: string;
        /**
         * @description The share group\'s detailed description.
         * @type string
        */
        description: string | null;
        /**
         * @description __Read-only__ When the share group expires.
         * @type string, date-time
        */
        readonly expiry: string | null;
        /**
         * @description The share group\'s numeric identifier, used primarily as path parameters in URLs.
         * @type integer
        */
        id: number;
        /**
         * @description __Read-only__ The total number of images currently belonging to the share group.
         * @type integer
        */
        readonly images_count: number;
        /**
         * @description __Read-only__ Indicates whether the share group is currently suspended.
         * @type boolean
        */
        readonly is_suspended: boolean;
        /**
         * @description __Filterable__ The share group\'s descriptive name.
         * @type string
        */
        label: string;
        /**
         * @description __Read-only__ The number of users with access to the share group.
         * @type integer
        */
        readonly members_count: number;
        /**
         * @description __Read-only__ When this share group was last updated.
         * @type string, date-time
        */
        readonly updated: string | null;
        /**
         * @description The share group\'s unique identifier used for membership token management.
         * @type string, uuid
        */
        uuid: string;
    }[];
    /**
     * @description __Read-only__ The current [page](https://techdocs.akamai.com/linode-api/reference/pagination).
     * @type integer
    */
    readonly page: number;
    /**
     * @description __Read-only__ The total number of [pages](https://techdocs.akamai.com/linode-api/reference/pagination).
     * @type integer
    */
    readonly pages: number;
    /**
     * @description __Read-only__ The total number of results.
     * @type integer
    */
    readonly results: number;
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface GetImagesSharegroupsImageError {
    /**
     * @type array
    */
    errors: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string
        */
        field: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string
        */
        reason: string;
    }[];
}

export type GetImagesSharegroupsImageQueryResponse = GetImagesSharegroupsImage200;

export type GetImagesSharegroupsImageQuery = {
    Response: GetImagesSharegroupsImage200;
    PathParams: GetImagesSharegroupsImagePathParams;
    Errors: any;
};