/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface GetLongviewSubscriptionPathParams {
    /**
     * @description The Longview Subscription to look up.
     * @type string
    */
    subscriptionId: string;
}

export const getLongviewSubscription200IdEnum = {
    "longview-3": "longview-3",
    "longview-10": "longview-10",
    "longview-40": "longview-40",
    "longview-100": "longview-100"
} as const;

export type GetLongviewSubscription200IdEnumKey = (typeof getLongviewSubscription200IdEnum)[keyof typeof getLongviewSubscription200IdEnum];

/**
 * @description The requested Longview Subscription details.
*/
export interface GetLongviewSubscription200 {
    /**
     * @description __Read-only__ The number of Longview Clients that may be created with this Subscription tier.
     * @type integer
    */
    readonly clients_included: number;
    /**
     * @description __Read-only__ The unique ID of this Subscription tier.
     * @type string
    */
    readonly id: GetLongviewSubscription200IdEnumKey;
    /**
     * @description __Read-only__ A display name for this Subscription tier.
     * @type string
    */
    readonly label: string;
    /**
     * @description __Read-only__ Pricing information about this Subscription tier.
     * @type object
    */
    readonly price: {
        /**
         * @description __Read-only__ The hourly price, in US dollars, for this Subscription tier.
         * @type number
        */
        readonly hourly: number;
        /**
         * @description __Read-only__ The maximum monthly price in US Dollars for this Subscription tier. You will never be charged more than this amount per month for this subscription.
         * @type number
        */
        readonly monthly: number;
    };
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface GetLongviewSubscriptionError {
    /**
     * @type array
    */
    errors: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string
        */
        field: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string
        */
        reason: string;
    }[];
}

export type GetLongviewSubscriptionQueryResponse = GetLongviewSubscription200;

export type GetLongviewSubscriptionQuery = {
    Response: GetLongviewSubscription200;
    PathParams: GetLongviewSubscriptionPathParams;
    Errors: any;
};