/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description A list of Managed Stats from the last 24 hours.
*/
export interface GetManagedStats200 {
    /**
     * @type object
    */
    data: ({
        /**
         * @description CPU usage stats from the last 24 hours.
         * @type array
        */
        cpu: {
            /**
             * @description __Read-only__ A stats graph data point.
             * @type integer
            */
            readonly x: number;
            /**
             * @description __Read-only__ A stats graph data point.
             * @type integer
            */
            readonly y: number;
        }[];
        /**
         * @description Disk usage stats from the last 24 hours.
         * @type array
        */
        disk: {
            /**
             * @description __Read-only__ A stats graph data point.
             * @type integer
            */
            readonly x: number;
            /**
             * @description __Read-only__ A stats graph data point.
             * @type integer
            */
            readonly y: number;
        }[];
        /**
         * @description Inbound network traffic stats from the last 24 hours.
         * @type array
        */
        net_in: {
            /**
             * @description __Read-only__ A stats graph data point.
             * @type integer
            */
            readonly x: number;
            /**
             * @description __Read-only__ A stats graph data point.
             * @type integer
            */
            readonly y: number;
        }[];
        /**
         * @description Outbound network traffic stats from the last 24 hours.
         * @type array
        */
        net_out: {
            /**
             * @description __Read-only__ A stats graph data point.
             * @type integer
            */
            readonly x: number;
            /**
             * @description __Read-only__ A stats graph data point.
             * @type integer
            */
            readonly y: number;
        }[];
        /**
         * @description Swap usage stats from the last 24 hours.
         * @type array
        */
        swap: {
            /**
             * @description __Read-only__ A stats graph data point.
             * @type integer
            */
            readonly x: number;
            /**
             * @description __Read-only__ A stats graph data point.
             * @type integer
            */
            readonly y: number;
        }[];
    } | string[]);
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface GetManagedStatsError {
    /**
     * @type array
    */
    errors: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string
        */
        field: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string
        */
        reason: string;
    }[];
}

export type GetManagedStatsQueryResponse = GetManagedStats200;

export type GetManagedStatsQuery = {
    Response: GetManagedStats200;
    Errors: any;
};