/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface PostGetTokenPathParams {
    /**
     * @description The Akamai Cloud Computing service being monitored. To see your currently supported services, run the [List supported service types](https://techdocs.akamai.com/linode-api/reference/get-monitor-services) operation and store the appropriate `service_type`.
     * @type string
    */
    serviceType: string;
}

/**
 * @description The response provides the token.
*/
export interface PostGetToken200 {
    /**
     * @description A string representing the authentication token. This token is required for subsequent requests.
     * @type string
    */
    token: string;
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface PostGetTokenError {
    /**
     * @type array
    */
    errors: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string
        */
        field: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string
        */
        reason: string;
    }[];
}

export interface PostGetTokenMutationRequest {
    /**
     * @description The `id` for each individual entity from a `service_type`. Get this value by running the list operation for the appropriate entity. For example, if your entity is one of your PostgreSQL databases, run the [List PostgreSQL Managed Databases](https://techdocs.akamai.com/linode-api/reference/get-databases-postgre-sql-instances) operation and store the `id` for the appropriate database from the response.\n\n> 📘\n>\n> - This field is required and supports up to 100 total entries.\n>\n> - You need read access permission to all of the entities you include in the token. Run the [List a user\'s grants](https://techdocs.akamai.com/linode-api/reference/get-user-grants) operation to see the permission level for each entity in your account.
     * @type array
    */
    entity_ids: number[];
}

export type PostGetTokenMutationResponse = PostGetToken200;

export type PostGetTokenMutation = {
    Response: PostGetToken200;
    Request: PostGetTokenMutationRequest;
    PathParams: PostGetTokenPathParams;
    Errors: any;
};