/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface PostLinodeConfigInterfacesPathParams {
    /**
     * @description The `id` of the Linode.
     * @type integer
    */
    linodeId: number;
    /**
     * @description The `id` of the Configuration Profile.
     * @type integer
    */
    configId: number;
}

/**
 * @description Interfaces successfully reordered.
*/
export type PostLinodeConfigInterfaces200 = object;

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface PostLinodeConfigInterfacesError {
    /**
     * @type array
    */
    errors: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string
        */
        field: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string
        */
        reason: string;
    }[];
}

/**
 * @description The desired Interface order for the Configuration Profile.
*/
export interface PostLinodeConfigInterfacesMutationRequest {
    /**
     * @description An ordered array of existing Configuration Profile Interface `id`s.\n\n- All current Interface `id`s must be present in the array.\n- If the Configuration Profile contains Interfaces and is active on the Linode, the Linode must first be shut down prior to running this operation.\n- Reordering takes effect after rebooting the Linode with this Configuration Profile.\n\nThe position in the array determines which of the Linode\'s network Interfaces is configured:\n\n- First [0]:  eth0\n- Second [1]: eth1\n- Third [2]:  eth2
     * @type array
    */
    ids: number[];
}

export type PostLinodeConfigInterfacesMutationResponse = PostLinodeConfigInterfaces200;

export type PostLinodeConfigInterfacesMutation = {
    Response: PostLinodeConfigInterfaces200;
    Request: PostLinodeConfigInterfacesMutationRequest;
    PathParams: PostLinodeConfigInterfacesPathParams;
    Errors: any;
};