/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const postLongviewClientPathParamsApiVersionEnum = {
    "v4": "v4",
    "v4beta": "v4beta"
} as const;

export type PostLongviewClientPathParamsApiVersionEnumKey = (typeof postLongviewClientPathParamsApiVersionEnum)[keyof typeof postLongviewClientPathParamsApiVersionEnum];

export interface PostLongviewClientPathParams {
    /**
     * @description __Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.
     * @type string
    */
    apiVersion: PostLongviewClientPathParamsApiVersionEnumKey;
}

/**
 * @description Longview Client created successfully.
*/
export interface PostLongviewClient200 {
    /**
     * @description __Read-only__ The API key for this Client, used when configuring the Longview Client application on your Linode.\n\nReturns as `[REDACTED]` if you do not have read-write access to this client.
     * @type string | undefined
    */
    readonly api_key?: string;
    /**
     * @description __Read-only__ The apps this Client is monitoring on your Linode. This is configured when you install the Longview Client application, and is present here for information purposes only.
     * @type object | undefined
    */
    readonly apps?: {
        /**
         * @description __Read-only__ If `true`, the Apache Longview Client module is monitoring Apache on your server.
         * @type boolean | undefined
        */
        readonly apache?: boolean;
        /**
         * @description __Read-only__ If `true`, the MySQL Longview Client modules is monitoring MySQL on your server.
         * @type boolean | undefined
        */
        readonly mysql?: boolean;
        /**
         * @description __Read-only__ If `true`, the Nginx Longview Client module is monitoring Nginx on your server.
         * @type boolean | undefined
        */
        readonly nginx?: boolean;
    };
    /**
     * @description __Read-only__ When this Longview Client was created.
     * @type string | undefined, date-time
    */
    readonly created?: string;
    /**
     * @description __Read-only__ This Client\'s unique ID.
     * @type integer | undefined
    */
    readonly id?: number;
    /**
     * @description __Read-only__ The install code for this Client, used when configuring the Longview Client application on your Linode.\n\nReturns as `[REDACTED]` if you do not have read-write access to this client.
     * @type string | undefined
    */
    readonly install_code?: string;
    /**
     * @description __Filterable__ This Client\'s unique label. This is for display purposes only.
     * @minLength 3
     * @maxLength 32
     * @pattern [a-zA-Z0-9-_]{3,32}
     * @type string | undefined
    */
    label?: string;
    /**
     * @description __Read-only__ When this Longview Client was last updated.
     * @type string | undefined, date-time
    */
    readonly updated?: string;
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface PostLongviewClientError {
    /**
     * @type array | undefined
    */
    errors?: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string | undefined
        */
        field?: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string | undefined
        */
        reason?: string;
    }[];
}

/**
 * @description Information about the LongviewClient to create.
*/
export type PostLongviewClientMutationRequest = Omit<NonNullable<{
    /**
     * @description __Read-only__ The API key for this Client, used when configuring the Longview Client application on your Linode.\n\nReturns as `[REDACTED]` if you do not have read-write access to this client.
     * @type string | undefined
    */
    readonly api_key?: string;
    /**
     * @description __Read-only__ The apps this Client is monitoring on your Linode. This is configured when you install the Longview Client application, and is present here for information purposes only.
     * @type object | undefined
    */
    readonly apps?: {
        /**
         * @description __Read-only__ If `true`, the Apache Longview Client module is monitoring Apache on your server.
         * @type boolean | undefined
        */
        readonly apache?: boolean;
        /**
         * @description __Read-only__ If `true`, the MySQL Longview Client modules is monitoring MySQL on your server.
         * @type boolean | undefined
        */
        readonly mysql?: boolean;
        /**
         * @description __Read-only__ If `true`, the Nginx Longview Client module is monitoring Nginx on your server.
         * @type boolean | undefined
        */
        readonly nginx?: boolean;
    };
    /**
     * @description __Read-only__ When this Longview Client was created.
     * @type string | undefined, date-time
    */
    readonly created?: string;
    /**
     * @description __Read-only__ This Client\'s unique ID.
     * @type integer | undefined
    */
    readonly id?: number;
    /**
     * @description __Read-only__ The install code for this Client, used when configuring the Longview Client application on your Linode.\n\nReturns as `[REDACTED]` if you do not have read-write access to this client.
     * @type string | undefined
    */
    readonly install_code?: string;
    /**
     * @description __Filterable__ This Client\'s unique label. This is for display purposes only.
     * @minLength 3
     * @maxLength 32
     * @pattern [a-zA-Z0-9-_]{3,32}
     * @type string | undefined
    */
    label?: string;
    /**
     * @description __Read-only__ When this Longview Client was last updated.
     * @type string | undefined, date-time
    */
    readonly updated?: string;
}>, "api_key" | "apps" | "created" | "id" | "install_code" | "updated">;

export type PostLongviewClientMutationResponse = PostLongviewClient200;

export type PostLongviewClientMutation = {
    Response: PostLongviewClient200;
    Request: PostLongviewClientMutationRequest;
    PathParams: PostLongviewClientPathParams;
    Errors: any;
};