/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface PutLkeClusterAclPathParams {
    /**
     * @description ID of the Kubernetes cluster to look up.
     * @type integer
    */
    clusterId: number;
}

/**
 * @description Returns a single cluster\'s control plane access control list. The optional field `revision-id` provided will be reflected on GET response when (and only after) the ACL stanza is verified as enforced.
*/
export interface PutLkeClusterAcl200 {
    /**
     * @type object
    */
    acl: {
        /**
         * @type object
        */
        addresses: {
            ipv4: any;
            ipv6: any;
        };
        "revision-id": any;
    };
}

/**
 * @description If the cluster was not created or updated to enable the ACL feature, this request returns a 400 (Bad Request) error with an appropriate message, such as `Cluster does not support Control Plane ACL`.
*/
export interface PutLkeClusterAcl400 {
    /**
     * @type array
    */
    errors: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string
        */
        field: string;
        /**
         * @description A string explaining that the cluster does not support Control Plane ACL.
         * @type string
        */
        reason: string;
    }[];
}

/**
 * @description If the cluster does not exist, this request returns a 404 (Not Found) error.
*/
export interface PutLkeClusterAcl404 {
    /**
     * @type array
    */
    errors: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string
        */
        field: string;
        /**
         * @description A string explaining that the cluster does not exist.
         * @type string
        */
        reason: string;
    }[];
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface PutLkeClusterAclError {
    /**
     * @type array
    */
    errors: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string
        */
        field: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string
        */
        reason: string;
    }[];
}

/**
 * @description The fields to update the cluster.
*/
export interface PutLkeClusterAclMutationRequest {
    /**
     * @description Defines settings related to the IP-based ACL of the LKE cluster. The object requires the `enabled` and `addresses` keys. It also supports the optional key `revision-id`. The default policy is set to `ALLOW`, so that access controls are disabled. An empty object value (`{}`) sets default elements.
     * @type object | undefined
    */
    acl?: {
        /**
         * @description Supports keys `ipv4` and `ipv6`. Defaults to `{}`.
         * @type object | undefined
        */
        addresses?: {
            /**
             * @description A list of individual ipv4 addresses or CIDRs to ALLOW. Defaults to `[]`.
             * @type array | undefined
            */
            ipv4?: string[];
            /**
             * @description A list of individual ipv6 addresses or CIDRs to ALLOW. Defaults to `[]`.
             * @type array | undefined
            */
            ipv6?: string[];
        };
        /**
         * @description Defines a default policy. A value of `true` results in a default policy of `DENY`. A value of `false` results in a default policy of `ALLOW`, such as for disabled access controls. It defaults to `true`. Creating a cluster with ACL, or upgrading a cluster to use ACL for LKE, is an irreversible change. Once upgraded, you can only toggle access controls with this field.
         * @type boolean | undefined
        */
        enabled?: boolean;
        /**
         * @description Enables clients to track events related to ACL update requests and enforcements. Optional field. If omitted, defaults to a randomly generated string.
         * @type string | undefined
        */
        "revision-id"?: string;
    };
}

export type PutLkeClusterAclMutationResponse = PutLkeClusterAcl200;

export type PutLkeClusterAclMutation = {
    Response: PutLkeClusterAcl200;
    Request: PutLkeClusterAclMutationRequest;
    PathParams: PutLkeClusterAclPathParams;
    Errors: PutLkeClusterAcl400 | PutLkeClusterAcl404;
};