/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from "./.kubb/fetch.ts";
import type { UploadFileMutationRequest, UploadFileMutationResponse, UploadFilePathParams, AddPetMutationRequest, AddPetMutationResponse, AddPet405, UpdatePetMutationRequest, UpdatePetMutationResponse, UpdatePet400, UpdatePet404, UpdatePet405, FindPetsByStatusQueryResponse, FindPetsByStatusQueryParams, FindPetsByStatus400, FindPetsByTagsQueryResponse, FindPetsByTagsQueryParams, FindPetsByTags400, GetPetByIdQueryResponse, GetPetByIdPathParams, GetPetById400, GetPetById404, UpdatePetWithFormMutationRequest, UpdatePetWithFormMutationResponse, UpdatePetWithFormPathParams, UpdatePetWithForm405, DeletePetMutationResponse, DeletePetPathParams, DeletePetHeaderParams, DeletePet400, DeletePet404, GetInventoryQueryResponse, PlaceOrderMutationRequest, PlaceOrderMutationResponse, PlaceOrder400, GetOrderByIdQueryResponse, GetOrderByIdPathParams, GetOrderById400, GetOrderById404, DeleteOrderMutationResponse, DeleteOrderPathParams, DeleteOrder400, DeleteOrder404, CreateUsersWithListInputMutationRequest, CreateUsersWithListInputMutationResponse, GetUserByNameQueryResponse, GetUserByNamePathParams, GetUserByName400, GetUserByName404, UpdateUserMutationRequest, UpdateUserMutationResponse, UpdateUserPathParams, UpdateUser400, UpdateUser404, DeleteUserMutationResponse, DeleteUserPathParams, DeleteUser400, DeleteUser404, LoginUserQueryResponse, LoginUserQueryParams, LoginUser400, LogoutUserQueryResponse, CreateUsersWithArrayInputMutationRequest, CreateUsersWithArrayInputMutationResponse, CreateUserMutationRequest, CreateUserMutationResponse } from "./types.ts";
import { buildFormData } from "./.kubb/config.ts";
import { fetch } from "./.kubb/fetch.ts";

function getUploadFileUrl(petId: UploadFilePathParams["petId"]) {
  const res = { method: 'POST', url: `/pet/${petId}/uploadImage` as const }  
  return res
}

/**
 * @summary uploads an image
 * {@link /pet/:petId/uploadImage}
 */
export async function uploadFile(petId: UploadFilePathParams["petId"], data?: UploadFileMutationRequest, config: Partial<RequestConfig<UploadFileMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  const formData = buildFormData(requestData)  
  const res = await request<UploadFileMutationResponse, ResponseErrorConfig<Error>, UploadFileMutationRequest>({ method : "POST", url : getUploadFileUrl(petId).url.toString(), data : formData as FormData, ... requestConfig })  
  return res.data
}

function getAddPetUrl() {
  const res = { method: 'POST', url: `/pet` as const }  
  return res
}

/**
 * @summary Add a new pet to the store
 * {@link /pet}
 */
export async function addPet(data: AddPetMutationRequest, config: Partial<RequestConfig<AddPetMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AddPetMutationResponse, ResponseErrorConfig<AddPet405>, AddPetMutationRequest>({ method : "POST", url : getAddPetUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}

function getUpdatePetUrl() {
  const res = { method: 'PUT', url: `/pet` as const }  
  return res
}

/**
 * @summary Update an existing pet
 * {@link /pet}
 */
export async function updatePet(data: UpdatePetMutationRequest, config: Partial<RequestConfig<UpdatePetMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdatePetMutationResponse, ResponseErrorConfig<UpdatePet400 | UpdatePet404 | UpdatePet405>, UpdatePetMutationRequest>({ method : "PUT", url : getUpdatePetUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}

function getFindPetsByStatusUrl() {
  const res = { method: 'GET', url: `/pet/findByStatus` as const }  
  return res
}

/**
 * @description Multiple status values can be provided with comma separated strings
 * @summary Finds Pets by status
 * {@link /pet/findByStatus}
 */
export async function findPetsByStatus(params: FindPetsByStatusQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<FindPetsByStatusQueryResponse, ResponseErrorConfig<FindPetsByStatus400>, unknown>({ method : "GET", url : getFindPetsByStatusUrl().url.toString(), params, ... requestConfig })  
  return res.data
}

function getFindPetsByTagsUrl() {
  const res = { method: 'GET', url: `/pet/findByTags` as const }  
  return res
}

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 * @deprecated
 */
export async function findPetsByTags(params: FindPetsByTagsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<FindPetsByTagsQueryResponse, ResponseErrorConfig<FindPetsByTags400>, unknown>({ method : "GET", url : getFindPetsByTagsUrl().url.toString(), params, ... requestConfig })  
  return res.data
}

function getGetPetByIdUrl(petId: GetPetByIdPathParams["petId"]) {
  const res = { method: 'GET', url: `/pet/${petId}` as const }  
  return res
}

/**
 * @description Returns a single pet
 * @summary Find pet by ID
 * {@link /pet/:petId}
 */
export async function getPetById(petId: GetPetByIdPathParams["petId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetPetByIdQueryResponse, ResponseErrorConfig<GetPetById400 | GetPetById404>, unknown>({ method : "GET", url : getGetPetByIdUrl(petId).url.toString(), ... requestConfig })  
  return res.data
}

function getUpdatePetWithFormUrl(petId: UpdatePetWithFormPathParams["petId"]) {
  const res = { method: 'POST', url: `/pet/${petId}` as const }  
  return res
}

/**
 * @summary Updates a pet in the store with form data
 * {@link /pet/:petId}
 */
export async function updatePetWithForm(petId: UpdatePetWithFormPathParams["petId"], data?: UpdatePetWithFormMutationRequest, config: Partial<RequestConfig<UpdatePetWithFormMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdatePetWithFormMutationResponse, ResponseErrorConfig<UpdatePetWithForm405>, UpdatePetWithFormMutationRequest>({ method : "POST", url : getUpdatePetWithFormUrl(petId).url.toString(), data : requestData, ... requestConfig, headers : { 'Content-Type': 'application/x-www-form-urlencoded', ...requestConfig.headers } })  
  return res.data
}

function getDeletePetUrl(petId: DeletePetPathParams["petId"]) {
  const res = { method: 'DELETE', url: `/pet/${petId}` as const }  
  return res
}

/**
 * @summary Deletes a pet
 * {@link /pet/:petId}
 */
export async function deletePet(petId: DeletePetPathParams["petId"], headers?: DeletePetHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeletePetMutationResponse, ResponseErrorConfig<DeletePet400 | DeletePet404>, unknown>({ method : "DELETE", url : getDeletePetUrl(petId).url.toString(), ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res.data
}

function getGetInventoryUrl() {
  const res = { method: 'GET', url: `/store/inventory` as const }  
  return res
}

/**
 * @description Returns a map of status codes to quantities
 * @summary Returns pet inventories by status
 * {@link /store/inventory}
 */
export async function getInventory(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetInventoryQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetInventoryUrl().url.toString(), ... requestConfig })  
  return res.data
}

function getPlaceOrderUrl() {
  const res = { method: 'POST', url: `/store/order` as const }  
  return res
}

/**
 * @summary Place an order for a pet
 * {@link /store/order}
 */
export async function placeOrder(data?: PlaceOrderMutationRequest, config: Partial<RequestConfig<PlaceOrderMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PlaceOrderMutationResponse, ResponseErrorConfig<PlaceOrder400>, PlaceOrderMutationRequest>({ method : "POST", url : getPlaceOrderUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}

function getGetOrderByIdUrl(orderId: GetOrderByIdPathParams["orderId"]) {
  const res = { method: 'GET', url: `/store/order/${orderId}` as const }  
  return res
}

/**
 * @description For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions
 * @summary Find purchase order by ID
 * {@link /store/order/:orderId}
 */
export async function getOrderById(orderId: GetOrderByIdPathParams["orderId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetOrderByIdQueryResponse, ResponseErrorConfig<GetOrderById400 | GetOrderById404>, unknown>({ method : "GET", url : getGetOrderByIdUrl(orderId).url.toString(), ... requestConfig })  
  return res.data
}

function getDeleteOrderUrl(orderId: DeleteOrderPathParams["orderId"]) {
  const res = { method: 'DELETE', url: `/store/order/${orderId}` as const }  
  return res
}

/**
 * @description For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors
 * @summary Delete purchase order by ID
 * {@link /store/order/:orderId}
 */
export async function deleteOrder(orderId: DeleteOrderPathParams["orderId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteOrderMutationResponse, ResponseErrorConfig<DeleteOrder400 | DeleteOrder404>, unknown>({ method : "DELETE", url : getDeleteOrderUrl(orderId).url.toString(), ... requestConfig })  
  return res.data
}

function getCreateUsersWithListInputUrl() {
  const res = { method: 'POST', url: `/user/createWithList` as const }  
  return res
}

/**
 * @summary Creates list of users with given input array
 * {@link /user/createWithList}
 */
export async function createUsersWithListInput(data?: CreateUsersWithListInputMutationRequest, config: Partial<RequestConfig<CreateUsersWithListInputMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateUsersWithListInputMutationResponse, ResponseErrorConfig<Error>, CreateUsersWithListInputMutationRequest>({ method : "POST", url : getCreateUsersWithListInputUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}

function getGetUserByNameUrl(username: GetUserByNamePathParams["username"]) {
  const res = { method: 'GET', url: `/user/${username}` as const }  
  return res
}

/**
 * @summary Get user by user name
 * {@link /user/:username}
 */
export async function getUserByName(username: GetUserByNamePathParams["username"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetUserByNameQueryResponse, ResponseErrorConfig<GetUserByName400 | GetUserByName404>, unknown>({ method : "GET", url : getGetUserByNameUrl(username).url.toString(), ... requestConfig })  
  return res.data
}

function getUpdateUserUrl(username: UpdateUserPathParams["username"]) {
  const res = { method: 'PUT', url: `/user/${username}` as const }  
  return res
}

/**
 * @description This can only be done by the logged in user.
 * @summary Updated user
 * {@link /user/:username}
 */
export async function updateUser(username: UpdateUserPathParams["username"], data?: UpdateUserMutationRequest, config: Partial<RequestConfig<UpdateUserMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateUserMutationResponse, ResponseErrorConfig<UpdateUser400 | UpdateUser404>, UpdateUserMutationRequest>({ method : "PUT", url : getUpdateUserUrl(username).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}

function getDeleteUserUrl(username: DeleteUserPathParams["username"]) {
  const res = { method: 'DELETE', url: `/user/${username}` as const }  
  return res
}

/**
 * @description This can only be done by the logged in user.
 * @summary Delete user
 * {@link /user/:username}
 */
export async function deleteUser(username: DeleteUserPathParams["username"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteUserMutationResponse, ResponseErrorConfig<DeleteUser400 | DeleteUser404>, unknown>({ method : "DELETE", url : getDeleteUserUrl(username).url.toString(), ... requestConfig })  
  return res.data
}

function getLoginUserUrl() {
  const res = { method: 'GET', url: `/user/login` as const }  
  return res
}

/**
 * @summary Logs user into the system
 * {@link /user/login}
 */
export async function loginUser(params: LoginUserQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<LoginUserQueryResponse, ResponseErrorConfig<LoginUser400>, unknown>({ method : "GET", url : getLoginUserUrl().url.toString(), params, ... requestConfig })  
  return res.data
}

function getLogoutUserUrl() {
  const res = { method: 'GET', url: `/user/logout` as const }  
  return res
}

/**
 * @summary Logs out current logged in user session
 * {@link /user/logout}
 */
export async function logoutUser(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<LogoutUserQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getLogoutUserUrl().url.toString(), ... requestConfig })  
  return res.data
}

function getCreateUsersWithArrayInputUrl() {
  const res = { method: 'POST', url: `/user/createWithArray` as const }  
  return res
}

/**
 * @summary Creates list of users with given input array
 * {@link /user/createWithArray}
 */
export async function createUsersWithArrayInput(data?: CreateUsersWithArrayInputMutationRequest, config: Partial<RequestConfig<CreateUsersWithArrayInputMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateUsersWithArrayInputMutationResponse, ResponseErrorConfig<Error>, CreateUsersWithArrayInputMutationRequest>({ method : "POST", url : getCreateUsersWithArrayInputUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}

function getCreateUserUrl() {
  const res = { method: 'POST', url: `/user` as const }  
  return res
}

/**
 * @description This can only be done by the logged in user.
 * @summary Create user
 * {@link /user}
 */
export async function createUser(data?: CreateUserMutationRequest, config: Partial<RequestConfig<CreateUserMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateUserMutationResponse, ResponseErrorConfig<Error>, CreateUserMutationRequest>({ method : "POST", url : getCreateUserUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}