/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Account Service Availability object.
 */
export const accountAvailabilitySchema = z.object({
    "available": z.optional(z.array(z.string()).describe("__Read-only__ A list of services _available_ to your account in the `region`.")),
"region": z.optional(z.string().describe("__Read-only__ The Akamai cloud computing data center (region), represented by a slug value. You can view a full list of regions and their associated slugs with the [List regions](https://techdocs.akamai.com/linode-api/reference/get-regions) operation.")),
"unavailable": z.optional(z.array(z.string()).describe("__Read-only__ A list of services _unavailable_ to your account in the `region`."))
    }).describe("Account Service Availability object.")