/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const getAvailabilityPathParamsSchema = z.object({
    "apiVersion": z.enum(["v4", "v4beta"]).describe("__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
    })

export const getAvailabilityQueryParamsSchema = z.object({
    "page": z.coerce.number().int().min(1).default(1).describe("The page of a collection to return."),
"page_size": z.coerce.number().int().min(25).max(500).default(100).describe("The number of items to return per page.")
    })

/**
 * @description List of regions and the services available in each.
 */
export const getAvailability200Schema = z.object({
    "data": z.optional(z.array(z.object({
    "available": z.optional(z.array(z.string()).describe("__Read-only__ A list of services _available_ to your account in the `region`.")),
"region": z.optional(z.string().describe("__Read-only__ The Akamai cloud computing data center (region), represented by a slug value. You can view a full list of regions and their associated slugs with the [List regions](https://techdocs.akamai.com/linode-api/reference/get-regions) operation.")),
"unavailable": z.optional(z.array(z.string()).describe("__Read-only__ A list of services _unavailable_ to your account in the `region`."))
    }).describe("Account Service Availability object."))),
"page": z.optional(z.int().describe("__Read-only__ The current [page](https://techdocs.akamai.com/linode-api/reference/pagination).")),
"pages": z.optional(z.int().describe("__Read-only__ The total number of [pages](https://techdocs.akamai.com/linode-api/reference/pagination).")),
"results": z.optional(z.int().describe("__Read-only__ The total number of results."))
    })

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export const getAvailabilityErrorSchema = z.object({
    "errors": z.optional(z.array(z.object({
    "field": z.optional(z.string().describe("The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.")),
"reason": z.optional(z.string().describe("What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully."))
    }).describe("An object for describing a single error that occurred during the processing of a request.")))
    })

export const getAvailabilityQueryResponseSchema = z.lazy(() => getAvailability200Schema)