/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const postLkeClusterRegeneratePathParamsSchema = z.object({
    "clusterId": z.coerce.number().int().describe("ID of the target Kubernetes cluster.")
    })

/**
 * @description Regenerate request successful.
 */
export const postLkeClusterRegenerate200Schema = z.object({
    
    }).describe("The API responds with an empty object.")

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export const postLkeClusterRegenerateErrorSchema = z.object({
    "errors": z.array(z.object({
    "field": z.string().describe("The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request."),
"reason": z.string().describe("What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.")
    }).describe("An object for describing a single error that occurred during the processing of a request."))
    })

/**
 * @description The Kubernetes Cluster Regenerate request object.
 */
export const postLkeClusterRegenerateMutationRequestSchema = z.object({
    "kubeconfig": z.optional(z.boolean().default(false).describe("Whether to delete and regenerate the Kubeconfig file for this Cluster.")),
"servicetoken": z.optional(z.boolean().default(false).describe("Whether to delete and regenerate the service access token for this Cluster."))
    })

export const postLkeClusterRegenerateMutationResponseSchema = z.lazy(() => postLkeClusterRegenerate200Schema)