/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const putLinodeInterfacePathParamsSchema = z.object({
    "apiVersion": z.enum(["v4", "v4beta"]).describe("__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta."),
"linodeId": z.coerce.number().int().describe("The `id` of the Linode."),
"interfaceId": z.coerce.number().int().describe("The `id` of the Linode interface.")
    })

/**
 * @description The Linode interface was successfully updated.
 */
export const putLinodeInterface200Schema = z.union([z.object({
    "created": z.optional(z.string().datetime().describe("When the interface was created.")),
"default_route": z.object({
    "ipv4": z.optional(z.boolean().default(false).describe("Indicates if the interface is used for the IPv4 default route. Only one interface per Linode can have the IPv4 default route.")),
"ipv6": z.optional(z.boolean().default(false).describe("Indicates if the interface is used for the IPv6 default route. Only one interface per Linode can have the IPv6 default route."))
    }).describe("Indicates if the interface is used as a default route.").nullish(),
"id": z.optional(z.int().describe("__Read-only__ The unique ID for this interface. For `dry_run` [upgrades](https://techdocs.akamai.com/linode-api/reference/post-upgrade-linode-interfaces), a unique `id` is not generated for the interface and its value is set to 0.")),
"mac_address": z.optional(z.string().regex(/[a-zA-Z0-9-]+/).describe("A 48-bit MAC address used to identify the Linode’s interface. A public interface's `mac_address` does not change, even if the public interface is deleted and then recreated.")),
"public": z.optional(z.object({
    "ipv4": z.optional(z.object({
    "addresses": z.optional(z.array(z.object({
    "address": z.optional(z.string().describe("The public IPv4 address assigned to this interface.")),
"primary": z.optional(z.boolean().describe("Indicates if the public IPv4 address serves as the source address for traffic routing within the Linode and other corresponding network interfaces and services."))
    })).describe("The public IPv4 addresses and primary settings for this public interface.")),
"shared": z.optional(z.array(z.object({
    "address": z.optional(z.string().describe("Shared IPv4 address.")),
"linode_id": z.optional(z.string().describe("The ID of the Linode this address currently belongs to. For IPv4 addresses, by default this is the Linode this address was assigned when created."))
    })).describe("The IPv4 address assigned to this Linode interface, which is also shared with another Linode."))
    }).describe("The interface's public IPv4 `addresses`.")),
"ipv6": z.optional(z.object({
    "ranges": z.optional(z.array(z.object({
    "range": z.optional(z.string().describe("IPv6 range in CIDR notation (`2600:0db8::1/64`) or prefix-only (`/64`).")),
"route_target": z.optional(z.string().describe("The public IPv6 address that the `range` is routed to."))
    })).describe("List of IPv6 ranges assigned to this interface.")),
"shared": z.optional(z.array(z.object({
    "range": z.optional(z.string().describe("The IPv6 address range.")),
"route_target": z.optional(z.string().describe("The public IPv6 address that the `range` is routed to."))
    })).describe("The IPv6 address assigned to this Linode interface, which is also shared with another Linode.")),
"slaac": z.optional(z.array(z.object({
    "address": z.optional(z.string().describe("Public IPv6 addresses assigned to this interface.")),
"prefix": z.optional(z.int().describe("The prefix length advertised for SLAAC to use. Only the specific (`/128`) EUI-64 address derived from the interface's MAC address is supported. To ensure the MAC-based EUI-64 address is used, privacy addressing needs to be disabled. Network Helper automatically configures the MAC-derived EUI-64 address. If you disable Network Helper or use an unsupported operating system, follow the specific instructions for your OS."))
    })).describe("The public `slaac` and subnet prefix settings for this public interface that is used to communicate over the public internet, and with other services in the same data center."))
    }).describe("The interface's public IPv6 configuration."))
    }).describe("Public interface type.")),
"updated": z.optional(z.string().datetime().describe("When the interface was last updated.")),
"version": z.optional(z.int().describe("Interface version number that increments when the interface updates.")),
"vlan": z.object({
    
    }).describe("The value is `null` if this is not a VLAN interface.").nullish(),
"vpc": z.object({
    
    }).describe("The value is `null` if this is not a VPC interface.").nullish()
    }), z.object({
    "created": z.optional(z.string().datetime().describe("When the interface was created.")),
"id": z.optional(z.int().describe("__Read-only__ The unique ID for this interface. For `dry_run` [upgrades](https://techdocs.akamai.com/linode-api/reference/post-upgrade-linode-interfaces), a unique `id` is not generated for the interface and its value is set to 0.")),
"mac_address": z.optional(z.string().regex(/[a-zA-Z0-9-]+/).describe("A 48-bit MAC address used to identify the Linode’s interface. The `mac_address` of an interface remains constant and does not change.")),
"public": z.object({
    
    }).describe("The value is `null` if this isn't a public interface.").nullish(),
"updated": z.optional(z.string().datetime().describe("When the interface was last updated.")),
"version": z.optional(z.int().describe("Interface version number that is incremented when the interface is updated.")),
"vlan": z.optional(z.object({
    "ipam_address": z.string().describe("This VLAN interface's private IPv4 address in classless inter-domain routing (CIDR) notation.").nullish(),
"vlan_label": z.optional(z.string().describe("The VLAN's label. VLAN interfaces on the same Linode must have a unique `vlan_label`."))
    }).describe("VLAN interface type.")),
"vpc": z.object({
    
    }).describe("The value is `null` if this isn't a VPC interface.").nullish()
    }), z.object({
    "created": z.optional(z.string().datetime().describe("When the interface was created.")),
"default_route": z.optional(z.object({
    "ipv4": z.optional(z.boolean().default(false).describe("Indicates if the interface serves as the IPv4 default route. Only one interface per Linode can have the IPv4 default route."))
    }).describe("Indicates if the interface serves as a default route.")),
"id": z.optional(z.int().describe("__Read-only__ The unique ID for this interface. For `dry_run` [upgrades](https://techdocs.akamai.com/linode-api/reference/post-upgrade-linode-interfaces), a unique `id` is not generated for the interface and its value is set to 0.")),
"mac_address": z.optional(z.string().regex(/[a-zA-Z0-9-]+/).describe("A 48-bit MAC address used to identify the Linode’s interface. The `mac_address` of an interface remains constant and does not change.")),
"public": z.object({
    
    }).describe("The value is `null` if this is not a public interface.").nullish(),
"updated": z.optional(z.string().datetime().describe("When the interface last updated.")),
"version": z.optional(z.int().describe("The version number of the interface configuration, incremented each time the interface is updated.")),
"vlan": z.object({
    
    }).describe("The value is `null` if this is not a VLAN interface.").nullish(),
"vpc": z.optional(z.object({
    "ipv4": z.optional(z.object({
    "addresses": z.optional(z.array(z.object({
    "address": z.optional(z.string().describe("The VPC subnet IPv4 address.")),
"nat_1_1_address": z.string().describe("The 1:1 NAT IPv4 address used to associate a public IPv4 address with the interface's VPC subnet IPv4 address.").nullish(),
"primary": z.optional(z.boolean().describe("Indicates if the IPv4 address is used to set up a source address for routes inside the Linode for the corresponding network interface."))
    })).describe("IPv4 address settings for this VPC interface.")),
"ranges": z.optional(z.array(z.object({
    "range": z.optional(z.string().describe("CIDR notation of a range (`1.2.3.4/24`) or prefix only (`/24`)."))
    })).describe("VPC IPv4 ranges."))
    }).describe("The interface's IPv4 `addresses` and `ranges` configuration.")),
"subnet_id": z.optional(z.int().describe("VPC subnet's unique identifier.")),
"vpc_id": z.optional(z.int().describe("VPC's unique identifier."))
    }).describe("VPC interface type."))
    })]).describe("One of the following interface types: VPC, public, or VLAN.")

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export const putLinodeInterfaceErrorSchema = z.object({
    "errors": z.optional(z.array(z.object({
    "field": z.optional(z.string().describe("The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.")),
"reason": z.optional(z.string().describe("What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully."))
    }).describe("An object for describing a single error that occurred during the processing of a request.")))
    })

export const putLinodeInterfaceMutationRequestSchema = z.union([z.object({
    "default_route": z.optional(z.object({
    "ipv4": z.boolean().describe("If set to `true`, and if the interface has at least one IPv4 address after the PUT request, the `default_route` role is assigned to the interface. If another interface is already configured as the default route, this setting removes that configuration. If the interface has an IPv4 address, the value cannot be set as `false`.").nullish(),
"ipv6": z.boolean().describe("If set to `true`, and if the interface has at least one IPv6 address after the PUT request, the `default_route` role is assigned to the interface. If another interface is already configured as the default route, this setting removes that configuration. If the interface has an IPv6 address, the value cannot be set as `false`.").nullish()
    }).describe("Defines whether IPv4 and IPv6 default routes are enabled for this interface. Public interfaces can have both an IPv4  and IPv6 `default_route`, provided they have at least one IP address of the corresponding type. If the `default_route` is omitted, (or set to `null`), no changes are made to the `default_route` configuration.")),
"public": z.object({
    "ipv4": z.optional(z.object({
    "addresses": z.optional(z.array(z.object({
    "address": z.optional(z.string().default("auto").describe("The public IPv4 address configuration for the interface. If set to `auto`, a public IPv4 address is allocated. If the address is a reserved or an automatically assigned public IP, the IP must be reserved or already assigned to a single Linode, and it can’t be already assigned to an interface.")),
"primary": z.boolean().describe("The IPv4 primary address for the interface that is used to set up a source address for routes inside the Linode for the corresponding network interface.\nAutomatically set to `true` and should not be set to `false` if there is only one address present in the addresses array.\nIf more than one address is provided, primary must be set to `true` for one address.").nullish()
    })).describe("List of IPv4 addresses to assign to this interface. When updating the addresses, all addresses must be explicitly listed in the array, and any addresses not included in the update are removed. If omitted or set to `null`, no changes are made to the existing IPv4 configuration."))
    }).describe("IPv4 address settings for this public interface.")),
"ipv6": z.optional(z.object({
    "ranges": z.optional(z.array(z.object({
    "range": z.string().default({}).describe("IPv6 range in CIDR notation (`2001:0db8::1/64`) or prefix-only (`/64`).\n- The prefix of /64 or /56 block of IPv6 addresses.\n- CIDR notation ranges must be within your assigned ranges.")
    })).describe("List of IPv6 address ranges to assign to this interface. If range is omitted, or set to `null`, no changes are made to the IPv6 ranges of the interface. If range is updated, specify all ranges in this array, otherwise, the currently assigned ranges will be removed."))
    }).describe("IPv6 address settings for the public interface."))
    }).describe("Public interface settings.").nullish()
    }), z.object({
    "vlan": z.optional(z.object({
    "ipam_address": z.string().describe("This VLAN interface's private IPv4 address in classless inter-domain routing (CIDR) notation. The `ipam_address` can't be updated. It needs to be the existing value, or `null`.").nullish(),
"vlan_label": z.optional(z.string().regex(/[a-zA-Z0-9-]+/).describe("The VLAN's label. Once you specify it, you can't update it."))
    }).describe("VLAN interface settings."))
    }), z.object({
    "default_route": z.optional(z.object({
    "ipv4": z.boolean().describe("If set to `true`, and if the interface has at least one IPv4 address after the `PUT` request, the `default_route` role is assigned to the interface. If another interface is already configured as the default route, this setting removes that configuration. If the interface has an IPv4 address, the value can't be set to `false`. If this is omitted, or set to `null`, no changes are made to the interface's IPv4 configuration.").nullish()
    }).describe("Indicates if the interface is used as the default route. A VPC interface can have an IPv4 `default_route`.")),
"vpc": z.object({
    "ipv4": z.optional(z.object({
    "addresses": z.optional(z.array(z.object({
    "address": z.string().default("auto").describe("Specifies which IPv4 addresses to use in the VPC subnet. You can't use an IPv4 address taken from another Linode or interface, or the first two or last two addresses in the VPC subnet. Setting `address` to `auto` automatically assigns an IP address from the subnet."),
"nat_1_1_address": z.optional(z.string().default({}).describe("The 1:1 NAT IPv4 address that links a public IPv4 address with the interface's VPC subnet IPv4 address.\n\n- You can set this to a specific public IPv4 address that's available on the Linode.\n\n- If set to `auto`, a public IPv4 address is automatically selected.\n\n- If a public IPv4 address or `auto` is specified, `primary` must be set to `true`.\n\n- A specified address can't be used on another Linode.\n\n- If the address is a reserved or an automatically assigned public IP, the IP must be reserved or already assigned to a single Linode, and not assigned to an interface.\n\n- Omitting this or setting it to `null` results in no 1:1 NAT configuration for the VPC interface.")),
"primary": z.boolean().describe("The IPv4 primary address for the interface that sets up a source address for routes inside the Linode for the corresponding network interface.\nAutomatically sets to `true` and should not be set to `false` if there is only one address present in the `addresses` array.\nIf more than one `address` is provided, `primary` must be set to `true` for one address.").nullish()
    })).describe("IPv4 configuration for this VPC interface. When updating the addresses, all addresses must be explicitly listed in the array, and any addresses not included in the update are removed. If omitted or set to `null`, no changes are made to the existing IPv4 configuration. However, if the `subnet_id` is updated, new default address values are applied.")),
"ranges": z.optional(z.array(z.object({
    "range": z.string().describe("CIDR notation of a range (`1.2.3.4/28`) or prefix only (`/28`):\n- When only the prefix is provided, then an available range of that size within the VPC's subnet is automatically selected.\n- If specified as CIDR notation, it must belong to the VPC subnet. All addresses in the range must not be taken by any other Linode or interfaces in the VPC subnet and must not include any of the first two or last two addresses of the VPC subnet.").nullish()
    })).describe("VPC IPv4 ranges. If you omit `ranges` or set it to `null`, the interface's IPv4 ranges remain unchanged. But if you update `ranges`, you need to specify all of them, otherwise currently assigned ranges are removed."))
    }).describe("Interfaces can be configured with IPv4 `addresses` or `ranges`. If this is omitted, or set to `null`, no changes are made to the IPv4 configuration.")),
"subnet_id": z.int().describe("The VPC subnet identifier for this interface. Your subnet’s VPC must be in the same data center (region) as the Linode. If the subnet is updated, the IP configuration should also be updated. If the subnet is updated without updating the IP configuration, defaults are applied.")
    }).describe("VPC interface settings.").nullish()
    })]).describe("Modifies an existing Linode interface. The interface type (`vpc`, `public`, `vlan`) can't be changed.")

export const putLinodeInterfaceMutationResponseSchema = z.lazy(() => putLinodeInterface200Schema)