/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteLinodeInstancePathParams, DeleteLinodeInstance200, DeleteLinodeInstanceError, DeleteLinodeInstanceMutationResponse } from "../types/DeleteLinodeInstance.ts";
import { faker } from "@faker-js/faker";

export function createDeleteLinodeInstancePathParams(data?: Partial<DeleteLinodeInstancePathParams>): DeleteLinodeInstancePathParams {
  
  return {
  ...{"linodeId": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description Delete successful.
 */
export function createDeleteLinodeInstance200(data?: Partial<DeleteLinodeInstance200>): DeleteLinodeInstance200 {
  
  return {
  ...{},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createDeleteLinodeInstanceError(data?: Partial<DeleteLinodeInstanceError>): DeleteLinodeInstanceError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createDeleteLinodeInstanceMutationResponse(data?: Partial<DeleteLinodeInstanceMutationResponse>): DeleteLinodeInstanceMutationResponse {
  
  return data || faker.helpers.arrayElement<any>([createDeleteLinodeInstance200()])
}