/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetLongviewPlan200, GetLongviewPlanError, GetLongviewPlanQueryResponse } from "../types/GetLongviewPlan.ts";
import { faker } from "@faker-js/faker";

/**
 * @description The Longview plan details for this account.
 */
export function createGetLongviewPlan200(data?: Partial<GetLongviewPlan200>): GetLongviewPlan200 {
  
  return {
  ...{"clients_included": faker.number.int(),"id": faker.helpers.arrayElement<NonNullable<GetLongviewPlan200>["id"]>(["longview-3", "longview-10", "longview-40", "longview-100"]),"label": faker.string.alpha(),"price": {"hourly": faker.number.float(),"monthly": faker.number.float()}},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createGetLongviewPlanError(data?: Partial<GetLongviewPlanError>): GetLongviewPlanError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createGetLongviewPlanQueryResponse(data?: Partial<GetLongviewPlanQueryResponse>): GetLongviewPlanQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetLongviewPlan200()])
}