/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetIpv6RangesPathParams, GetIpv6RangesQueryParams, GetIpv6Ranges200, GetIpv6RangesError, GetIpv6RangesQueryResponse } from "../types/GetIpv6Ranges.ts";
import { faker } from "@faker-js/faker";

export function createGetIpv6RangesPathParams(data?: Partial<GetIpv6RangesPathParams>): GetIpv6RangesPathParams {
  
  return {
  ...{"apiVersion": faker.helpers.arrayElement<NonNullable<GetIpv6RangesPathParams>["apiVersion"]>(["v4", "v4beta"])},
  ...data || {}
  }
}

export function createGetIpv6RangesQueryParams(data?: Partial<GetIpv6RangesQueryParams>): GetIpv6RangesQueryParams {
  
  return {
  ...{"page": faker.number.int({ min: 1 }),"page_size": faker.number.int({ min: 25, max: 500 })},
  ...data || {}
  }
}

/**
 * @description The IPv6 ranges on your Account.
 */
export function createGetIpv6Ranges200(data?: Partial<GetIpv6Ranges200>): GetIpv6Ranges200 {
  
  return {
  ...{"data": faker.helpers.multiple(() => ({"prefix": faker.number.int(),"range": faker.string.alpha(),"region": faker.string.alpha(),"route_target": faker.string.alpha()})),"page": faker.number.int(),"pages": faker.number.int(),"results": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createGetIpv6RangesError(data?: Partial<GetIpv6RangesError>): GetIpv6RangesError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createGetIpv6RangesQueryResponse(data?: Partial<GetIpv6RangesQueryResponse>): GetIpv6RangesQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetIpv6Ranges200()])
}