/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetImagesQueryParams, GetImages200, GetImagesError, GetImagesQueryResponse } from "../types/GetImages.ts";
import { faker } from "@faker-js/faker";

export function createGetImagesQueryParams(data?: Partial<GetImagesQueryParams>): GetImagesQueryParams {
  
  return {
  ...{"page": faker.number.int({ min: 1 }),"page_size": faker.number.int({ min: 25, max: 500 })},
  ...data || {}
  }
}

/**
 * @description A paginated list of images.
 */
export function createGetImages200(data?: Partial<GetImages200>): GetImages200 {
  
  return {
  ...{"data": faker.helpers.multiple(() => ({"capabilities": faker.helpers.multiple(() => (faker.string.alpha())),"created": faker.date.anytime().toISOString(),"created_by": faker.string.alpha(),"deprecated": faker.datatype.boolean(),"description": faker.string.alpha({ length: { min: 1, max: 65000 } }),"eol": faker.date.anytime().toISOString(),"expiry": faker.date.anytime().toISOString(),"id": faker.string.alpha(),"image_sharing": faker.helpers.arrayElement<any>([{"shared_by": {},"shared_with": {"sharegroup_count": faker.number.int(),"sharegroup_list_url": faker.string.alpha()}}, {"shared_by": {"sharegroup_id": faker.number.int(),"sharegroup_label": faker.string.alpha(),"sharegroup_uuid": faker.string.uuid(),"source_image_id": faker.string.alpha()},"shared_with": {}}]),"is_public": faker.datatype.boolean(),"is_shared": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<GetImages200>["data"]>[number]>["is_shared"]>(["true", "false", "none"]),"label": faker.string.alpha(),"regions": faker.helpers.multiple(() => ({"region": faker.string.alpha(),"status": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<NonNullable<NonNullable<GetImages200>["data"]>[number]>["regions"]>[number]>["status"]>(["available", "creating", "pending", "pending deletion", "pending replication", "replicating"])})),"size": faker.number.int(),"status": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<GetImages200>["data"]>[number]>["status"]>(["creating", "pending_upload", "available"]),"tags": faker.helpers.multiple(() => (faker.string.alpha({ length: { min: 3, max: 100 } })), { count: { min: 0, max: 500 }}),"total_size": faker.number.int(),"type": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<GetImages200>["data"]>[number]>["type"]>(["manual", "automatic", "shared"]),"updated": faker.date.anytime().toISOString(),"vendor": faker.string.alpha()})),"page": faker.number.int(),"pages": faker.number.int(),"results": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createGetImagesError(data?: Partial<GetImagesError>): GetImagesError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createGetImagesQueryResponse(data?: Partial<GetImagesQueryResponse>): GetImagesQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetImages200()])
}