/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PutLkeClusterAclPathParams, PutLkeClusterAcl200, PutLkeClusterAcl400, PutLkeClusterAcl404, PutLkeClusterAclError, PutLkeClusterAclMutationRequest, PutLkeClusterAclMutationResponse } from "../types/PutLkeClusterAcl.ts";
import { faker } from "@faker-js/faker";

export function createPutLkeClusterAclPathParams(data?: Partial<PutLkeClusterAclPathParams>): PutLkeClusterAclPathParams {
  
  return {
  ...{"clusterId": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description Returns a single cluster\'s control plane access control list. The optional field `revision-id` provided will be reflected on GET response when (and only after) the ACL stanza is verified as enforced.
 */
export function createPutLkeClusterAcl200(data?: Partial<PutLkeClusterAcl200>): PutLkeClusterAcl200 {
  
  return Object.assign({}, {"acl": {"addresses": {"ipv4": undefined,"ipv6": undefined},"revision-id": undefined}})
}

/**
 * @description If the cluster was not created or updated to enable the ACL feature, this request returns a 400 (Bad Request) error with an appropriate message, such as `Cluster does not support Control Plane ACL`.
 */
export function createPutLkeClusterAcl400(data?: Partial<PutLkeClusterAcl400>): PutLkeClusterAcl400 {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

/**
 * @description If the cluster does not exist, this request returns a 404 (Not Found) error.
 */
export function createPutLkeClusterAcl404(data?: Partial<PutLkeClusterAcl404>): PutLkeClusterAcl404 {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createPutLkeClusterAclError(data?: Partial<PutLkeClusterAclError>): PutLkeClusterAclError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

/**
 * @description The fields to update the cluster.
 */
export function createPutLkeClusterAclMutationRequest(data?: Partial<PutLkeClusterAclMutationRequest>): PutLkeClusterAclMutationRequest {
  
  return {
  ...{"acl": {"addresses": {"ipv4": faker.helpers.multiple(() => (faker.string.alpha())),"ipv6": faker.helpers.multiple(() => (faker.string.alpha()))},"enabled": faker.datatype.boolean(),"revision-id": faker.string.alpha()}},
  ...data || {}
  }
}

export function createPutLkeClusterAclMutationResponse(data?: Partial<PutLkeClusterAclMutationResponse>): PutLkeClusterAclMutationResponse {
  
  return data || faker.helpers.arrayElement<any>([createPutLkeClusterAcl200()])
}