/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteDatabasesPostgreSqlInstancePathParams, DeleteDatabasesPostgreSqlInstance200, DeleteDatabasesPostgreSqlInstanceError, DeleteDatabasesPostgreSqlInstanceMutationResponse } from "../types/DeleteDatabasesPostgreSqlInstance.ts";
import { faker } from "@faker-js/faker";

export function createDeleteDatabasesPostgreSqlInstancePathParams(data?: Partial<DeleteDatabasesPostgreSqlInstancePathParams>): DeleteDatabasesPostgreSqlInstancePathParams {
  
  return {
  ...{"instanceId": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description PostgreSQL Managed Database successfully deleted.
 */
export function createDeleteDatabasesPostgreSqlInstance200(data?: Partial<DeleteDatabasesPostgreSqlInstance200>): DeleteDatabasesPostgreSqlInstance200 {
  
  return {
  ...{},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createDeleteDatabasesPostgreSqlInstanceError(data?: Partial<DeleteDatabasesPostgreSqlInstanceError>): DeleteDatabasesPostgreSqlInstanceError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createDeleteDatabasesPostgreSqlInstanceMutationResponse(data?: Partial<DeleteDatabasesPostgreSqlInstanceMutationResponse>): DeleteDatabasesPostgreSqlInstanceMutationResponse {
  
  return data || faker.helpers.arrayElement<any>([createDeleteDatabasesPostgreSqlInstance200()])
}