/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetDomainRecordsPathParams, GetDomainRecordsQueryParams, GetDomainRecords200, GetDomainRecordsQueryResponse } from "../types/GetDomainRecords.ts";
import { faker } from "@faker-js/faker";

export function createGetDomainRecordsPathParams(data?: Partial<GetDomainRecordsPathParams>): GetDomainRecordsPathParams {
  
  return {
  ...{"apiVersion": faker.helpers.arrayElement<NonNullable<GetDomainRecordsPathParams>["apiVersion"]>(["v4", "v4beta"]),"domainId": faker.number.int()},
  ...data || {}
  }
}

export function createGetDomainRecordsQueryParams(data?: Partial<GetDomainRecordsQueryParams>): GetDomainRecordsQueryParams {
  
  return {
  ...{"page": faker.number.int({ min: 1 }),"page_size": faker.number.int({ min: 25, max: 500 })},
  ...data || {}
  }
}

/**
 * @description A list of Domain Records.
 */
export function createGetDomainRecords200(data?: Partial<GetDomainRecords200>): GetDomainRecords200 {
  
  return {
  ...{"data": faker.helpers.multiple(() => ({"created": faker.date.anytime().toISOString(),"id": faker.number.int(),"name": faker.string.alpha({ length: { min: 1, max: 100 } }),"port": faker.number.int({ min: 0, max: 65535 }),"priority": faker.number.int({ min: 0, max: 255 }),"protocol": faker.string.alpha(),"service": faker.string.alpha(),"tag": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<GetDomainRecords200>["data"]>[number]>["tag"]>(["issue", "issuewild", "iodef"]),"target": faker.string.alpha({ length: 65535 }),"ttl_sec": faker.number.int(),"type": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<GetDomainRecords200>["data"]>[number]>["type"]>(["A", "AAAA", "NS", "MX", "CNAME", "TXT", "SRV", "PTR", "CAA"]),"updated": faker.date.anytime().toISOString(),"weight": faker.number.int({ min: 0, max: 65535 })})),"page": faker.number.int(),"pages": faker.number.int(),"results": faker.number.int()},
  ...data || {}
  }
}

export function createGetDomainRecordsQueryResponse(data?: Partial<GetDomainRecordsQueryResponse>): GetDomainRecordsQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetDomainRecords200()])
}