/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetNodeBalancerConfigNodesPathParams, GetNodeBalancerConfigNodesQueryParams, GetNodeBalancerConfigNodes200, GetNodeBalancerConfigNodesError, GetNodeBalancerConfigNodesQueryResponse } from "../types/GetNodeBalancerConfigNodes.ts";
import { faker } from "@faker-js/faker";

export function createGetNodeBalancerConfigNodesPathParams(data?: Partial<GetNodeBalancerConfigNodesPathParams>): GetNodeBalancerConfigNodesPathParams {
  
  return {
  ...{"nodeBalancerId": faker.number.int(),"configId": faker.number.int()},
  ...data || {}
  }
}

export function createGetNodeBalancerConfigNodesQueryParams(data?: Partial<GetNodeBalancerConfigNodesQueryParams>): GetNodeBalancerConfigNodesQueryParams {
  
  return {
  ...{"page": faker.number.int({ min: 1 }),"page_size": faker.number.int({ min: 25, max: 500 })},
  ...data || {}
  }
}

/**
 * @description A paginated list of NodeBalancer nodes.
 */
export function createGetNodeBalancerConfigNodes200(data?: Partial<GetNodeBalancerConfigNodes200>): GetNodeBalancerConfigNodes200 {
  
  return {
  ...{"data": faker.helpers.multiple(() => (faker.helpers.arrayElement<any>([{"address": faker.string.alpha(),"config_id": faker.number.int(),"id": faker.number.int(),"label": faker.helpers.fromRegExp("[a-zA-Z0-9-_.]{3,32}"),"mode": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<GetNodeBalancerConfigNodes200>["data"]>[number]>["mode"]>(["accept", "reject", "drain", "backup"]),"nodebalancer_id": faker.number.int(),"status": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<GetNodeBalancerConfigNodes200>["data"]>[number]>["status"]>(["Unknown", "UP", "DOWN"]),"vpc_config_id": faker.number.int(),"weight": faker.number.int({ min: 1, max: 255 })}, {"address": faker.string.alpha(),"config_id": faker.number.int(),"id": faker.number.int(),"label": faker.helpers.fromRegExp("[a-zA-Z0-9-_.]{3,32}"),"mode": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<GetNodeBalancerConfigNodes200>["data"]>[number]>["mode"]>(["none"]),"nodebalancer_id": faker.number.int(),"status": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<GetNodeBalancerConfigNodes200>["data"]>[number]>["status"]>(["Unknown", "UP", "DOWN"]),"vpc_config_id": faker.number.int(),"weight": faker.number.int({ min: 1, max: 255 })}]))),"page": faker.number.int(),"pages": faker.number.int(),"results": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createGetNodeBalancerConfigNodesError(data?: Partial<GetNodeBalancerConfigNodesError>): GetNodeBalancerConfigNodesError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createGetNodeBalancerConfigNodesQueryResponse(data?: Partial<GetNodeBalancerConfigNodesQueryResponse>): GetNodeBalancerConfigNodesQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetNodeBalancerConfigNodes200()])
}