/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetTicketRepliesPathParams, GetTicketRepliesQueryParams, GetTicketReplies200, GetTicketRepliesError, GetTicketRepliesQueryResponse } from "../types/GetTicketReplies.ts";
import { faker } from "@faker-js/faker";

export function createGetTicketRepliesPathParams(data?: Partial<GetTicketRepliesPathParams>): GetTicketRepliesPathParams {
  
  return {
  ...{"ticketId": faker.number.int()},
  ...data || {}
  }
}

export function createGetTicketRepliesQueryParams(data?: Partial<GetTicketRepliesQueryParams>): GetTicketRepliesQueryParams {
  
  return {
  ...{"page": faker.number.int({ min: 1 }),"page_size": faker.number.int({ min: 25, max: 500 })},
  ...data || {}
  }
}

/**
 * @description Returns a paginated list of support ticket replies.
 */
export function createGetTicketReplies200(data?: Partial<GetTicketReplies200>): GetTicketReplies200 {
  
  return {
  ...{"data": faker.helpers.multiple(() => ({"created": faker.date.anytime().toISOString(),"created_by": faker.string.alpha(),"description": faker.string.alpha(),"from_linode": faker.datatype.boolean(),"gravatar_id": faker.string.alpha(),"id": faker.number.int()})),"page": faker.number.int(),"pages": faker.number.int(),"results": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createGetTicketRepliesError(data?: Partial<GetTicketRepliesError>): GetTicketRepliesError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createGetTicketRepliesQueryResponse(data?: Partial<GetTicketRepliesQueryResponse>): GetTicketRepliesQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetTicketReplies200()])
}