/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostChildAccountTokenPathParams, PostChildAccountToken200, PostChildAccountTokenError, PostChildAccountTokenMutationResponse } from "../types/PostChildAccountToken.ts";
import { faker } from "@faker-js/faker";

export function createPostChildAccountTokenPathParams(data?: Partial<PostChildAccountTokenPathParams>): PostChildAccountTokenPathParams {
  
  return {
  ...{"euuId": faker.string.alpha()},
  ...data || {}
  }
}

/**
 * @description Token created successfully.
 */
export function createPostChildAccountToken200(data?: Partial<PostChildAccountToken200>): PostChildAccountToken200 {
  
  return {
  ...{"created": faker.date.anytime().toISOString(),"expiry": faker.date.anytime().toISOString(),"id": faker.number.int(),"label": faker.string.alpha({ length: { min: 1, max: 100 } }),"scopes": faker.string.alpha(),"token": faker.string.alpha()},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createPostChildAccountTokenError(data?: Partial<PostChildAccountTokenError>): PostChildAccountTokenError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createPostChildAccountTokenMutationResponse(data?: Partial<PostChildAccountTokenMutationResponse>): PostChildAccountTokenMutationResponse {
  
  return data || faker.helpers.arrayElement<any>([createPostChildAccountToken200()])
}