/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetLinodeInterfaceHistoryPathParams, GetLinodeInterfaceHistory200, GetLinodeInterfaceHistoryError, GetLinodeInterfaceHistoryQueryResponse } from "../types/GetLinodeInterfaceHistory.ts";
import { faker } from "@faker-js/faker";

export function createGetLinodeInterfaceHistoryPathParams(data?: Partial<GetLinodeInterfaceHistoryPathParams>): GetLinodeInterfaceHistoryPathParams {
  
  return {
  ...{"apiVersion": faker.helpers.arrayElement<NonNullable<GetLinodeInterfaceHistoryPathParams>["apiVersion"]>(["v4", "v4beta"]),"linodeId": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description Returns a paginated list of network interface versions for a Linode.
 */
export function createGetLinodeInterfaceHistory200(data?: Partial<GetLinodeInterfaceHistory200>): GetLinodeInterfaceHistory200 {
  
  return {
  ...{"data": faker.helpers.multiple(() => ({"created": faker.date.anytime().toISOString(),"interface_data": faker.string.alpha(),"interface_history_id": faker.number.int(),"interface_id": faker.number.int(),"linode_id": faker.number.int(),"version": faker.number.int()})),"page": faker.number.int(),"pages": faker.number.int(),"results": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createGetLinodeInterfaceHistoryError(data?: Partial<GetLinodeInterfaceHistoryError>): GetLinodeInterfaceHistoryError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createGetLinodeInterfaceHistoryQueryResponse(data?: Partial<GetLinodeInterfaceHistoryQueryResponse>): GetLinodeInterfaceHistoryQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetLinodeInterfaceHistory200()])
}