/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetLinodeIpPathParams, GetLinodeIp200, GetLinodeIpError, GetLinodeIpQueryResponse } from "../types/GetLinodeIp.ts";
import { faker } from "@faker-js/faker";

export function createGetLinodeIpPathParams(data?: Partial<GetLinodeIpPathParams>): GetLinodeIpPathParams {
  
  return {
  ...{"linodeId": faker.number.int(),"address": faker.string.alpha()},
  ...data || {}
  }
}

/**
 * @description A single IP address.
 */
export function createGetLinodeIp200(data?: Partial<GetLinodeIp200>): GetLinodeIp200 {
  
  return {
  ...{"address": faker.string.alpha(),"gateway": faker.string.alpha(),"interface_id": faker.number.int(),"linode_id": faker.number.int(),"prefix": faker.number.int(),"public": faker.datatype.boolean(),"rdns": faker.string.alpha(),"region": faker.string.alpha(),"subnet_mask": faker.string.alpha(),"type": faker.helpers.arrayElement<NonNullable<GetLinodeIp200>["type"]>(["ipv4", "ipv6", "ipv6/pool", "ipv6/range"]),"vpc_nat_1_1": {"address": faker.internet.url(),"subnet_id": faker.number.int(),"vpc_id": faker.number.int()}},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createGetLinodeIpError(data?: Partial<GetLinodeIpError>): GetLinodeIpError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createGetLinodeIpQueryResponse(data?: Partial<GetLinodeIpQueryResponse>): GetLinodeIpQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetLinodeIp200()])
}