/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetSshKeyPathParams, GetSshKey200, GetSshKeyError, GetSshKeyQueryResponse } from "../types/GetSshKey.ts";
import { faker } from "@faker-js/faker";

export function createGetSshKeyPathParams(data?: Partial<GetSshKeyPathParams>): GetSshKeyPathParams {
  
  return {
  ...{"apiVersion": faker.helpers.arrayElement<NonNullable<GetSshKeyPathParams>["apiVersion"]>(["v4", "v4beta"]),"sshKeyId": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description An SSH Key object.
 */
export function createGetSshKey200(data?: Partial<GetSshKey200>): GetSshKey200 {
  
  return {
  ...{"created": faker.date.anytime().toISOString(),"id": faker.number.int(),"label": faker.string.alpha({ length: { min: 0, max: 64 } }),"ssh_key": faker.string.alpha()},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createGetSshKeyError(data?: Partial<GetSshKeyError>): GetSshKeyError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createGetSshKeyQueryResponse(data?: Partial<GetSshKeyQueryResponse>): GetSshKeyQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetSshKey200()])
}