/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PutLinodeInterfaceSettingsPathParams, PutLinodeInterfaceSettings200, PutLinodeInterfaceSettingsError, PutLinodeInterfaceSettingsMutationRequest, PutLinodeInterfaceSettingsMutationResponse } from "../types/PutLinodeInterfaceSettings.ts";
import { faker } from "@faker-js/faker";

export function createPutLinodeInterfaceSettingsPathParams(data?: Partial<PutLinodeInterfaceSettingsPathParams>): PutLinodeInterfaceSettingsPathParams {
  
  return {
  ...{"linodeId": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description The updated Linode interface settings.
 */
export function createPutLinodeInterfaceSettings200(data?: Partial<PutLinodeInterfaceSettings200>): PutLinodeInterfaceSettings200 {
  
  return {
  ...{"default_route": {"ipv4_eligible_interface_ids": faker.helpers.multiple(() => (faker.number.int())),"ipv4_interface_id": faker.number.int(),"ipv6_eligible_interface_ids": faker.helpers.multiple(() => (faker.number.int())),"ipv6_interface_id": faker.number.int()},"network_helper": faker.datatype.boolean()},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createPutLinodeInterfaceSettingsError(data?: Partial<PutLinodeInterfaceSettingsError>): PutLinodeInterfaceSettingsError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

/**
 * @description Update Linode interface settings. Before enabling or disabling Network Helper, you need to power off the Linode.
 */
export function createPutLinodeInterfaceSettingsMutationRequest(data?: Partial<PutLinodeInterfaceSettingsMutationRequest>): PutLinodeInterfaceSettingsMutationRequest {
  
  return {
  ...{"default_route": {"ipv4_eligible_interface_ids": faker.helpers.multiple(() => (faker.number.int())),"ipv4_interface_id": faker.number.int(),"ipv6_eligible_interface_ids": faker.helpers.multiple(() => (faker.number.int())),"ipv6_interface_id": faker.number.int()},"network_helper": faker.datatype.boolean()},
  ...data || {}
  }
}

export function createPutLinodeInterfaceSettingsMutationResponse(data?: Partial<PutLinodeInterfaceSettingsMutationResponse>): PutLinodeInterfaceSettingsMutationResponse {
  
  return data || faker.helpers.arrayElement<any>([createPutLinodeInterfaceSettings200()])
}