/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AddedPostPaymentMethod } from "../types/AddedPostPaymentMethod.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Payment Method Request Object.
 */
export function createAddedPostPaymentMethod(data?: Partial<AddedPostPaymentMethod>): AddedPostPaymentMethod {
  
  return {
  ...{"data": {"card_number": faker.string.alpha({ length: { min: 14, max: 24 } }),"cvv": faker.string.alpha({ length: { min: 3, max: 4 } }),"expiry_month": faker.number.int({ min: 1, max: 12 }),"expiry_year": faker.number.int({ min: 4, max: 4 })},"is_default": faker.datatype.boolean(),"type": faker.helpers.arrayElement<NonNullable<AddedPostPaymentMethod>["type"]>(["credit_card"])},
  ...data || {}
  }
}