/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostAccountAgreementsPathParams, PostAccountAgreements200, PostAccountAgreementsError, PostAccountAgreementsMutationRequest, PostAccountAgreementsMutationResponse } from "../types/PostAccountAgreements.ts";
import { faker } from "@faker-js/faker";

export function createPostAccountAgreementsPathParams(data?: Partial<PostAccountAgreementsPathParams>): PostAccountAgreementsPathParams {
  
  return {
  ...{"apiVersion": faker.helpers.arrayElement<NonNullable<PostAccountAgreementsPathParams>["apiVersion"]>(["v4", "v4beta"])},
  ...data || {}
  }
}

/**
 * @description Agreements updated successfully.
 */
export function createPostAccountAgreements200(data?: Partial<PostAccountAgreements200>): PostAccountAgreements200 {
  
  return {
  ...{},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createPostAccountAgreementsError(data?: Partial<PostAccountAgreementsError>): PostAccountAgreementsError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createPostAccountAgreementsMutationRequest(data?: Partial<PostAccountAgreementsMutationRequest>): PostAccountAgreementsMutationRequest {
  
  return {
  ...{"billing_agreement": faker.datatype.boolean(),"eu_model": faker.datatype.boolean(),"master_service_agreement": faker.datatype.boolean(),"privacy_policy": faker.datatype.boolean()},
  ...data || {}
  }
}

export function createPostAccountAgreementsMutationResponse(data?: Partial<PostAccountAgreementsMutationResponse>): PostAccountAgreementsMutationResponse {
  
  return data || faker.helpers.arrayElement<any>([createPostAccountAgreements200()])
}