/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetMaintenance200, GetMaintenanceError, GetMaintenanceQueryResponse } from "../types/GetMaintenance.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Returns a paginated list of Maintenance objects.
 */
export function createGetMaintenance200(data?: Partial<GetMaintenance200>): GetMaintenance200 {
  
  return {
  ...{"data": faker.helpers.multiple(() => ({"complete_time": faker.date.anytime().toISOString(),"description": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<GetMaintenance200>["data"]>[number]>["description"]>(["Scheduled Maintenance", "Emergency Maintenance"]),"entity": {"id": faker.number.float(),"label": faker.string.alpha(),"type": faker.string.alpha(),"url": faker.string.alpha()},"maintenance_policy_set": faker.string.alpha(),"not_before": faker.date.anytime().toISOString(),"reason": faker.string.alpha(),"source": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<GetMaintenance200>["data"]>[number]>["source"]>(["platform", "user"]),"start_time": faker.date.anytime().toISOString(),"status": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<GetMaintenance200>["data"]>[number]>["status"]>(["pending", "scheduled", "started", "in-progress", "completed", "canceled"]),"type": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<GetMaintenance200>["data"]>[number]>["type"]>(["reboot", "cold_migration", "live_migration", "migrate", "power_off_on"]),"when": faker.date.anytime().toISOString()})),"page": faker.number.int(),"pages": faker.number.int(),"results": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createGetMaintenanceError(data?: Partial<GetMaintenanceError>): GetMaintenanceError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createGetMaintenanceQueryResponse(data?: Partial<GetMaintenanceQueryResponse>): GetMaintenanceQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetMaintenance200()])
}