/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetRegionPathParams, GetRegion200, GetRegionError, GetRegionQueryResponse } from "../types/GetRegion.ts";
import { faker } from "@faker-js/faker";

export function createGetRegionPathParams(data?: Partial<GetRegionPathParams>): GetRegionPathParams {
  
  return {
  ...{"regionId": faker.string.alpha()},
  ...data || {}
  }
}

/**
 * @description A single Region object.
 */
export function createGetRegion200(data?: Partial<GetRegion200>): GetRegion200 {
  
  return {
  ...{"capabilities": faker.helpers.multiple(() => (faker.string.alpha())),"country": faker.string.alpha(),"id": faker.string.alpha(),"label": faker.string.alpha(),"monitors": {"alerts": faker.helpers.multiple(() => (faker.string.alpha())),"metrics": faker.helpers.multiple(() => (faker.string.alpha()))},"placement_group_limits": {"maximum_linodes_per_flexible_pg": faker.number.int(),"maximum_linodes_per_pg": faker.number.int(),"maximum_pgs_per_customer": faker.number.int()},"resolvers": {"ipv4": faker.string.alpha(),"ipv6": faker.string.alpha()},"site_type": faker.helpers.arrayElement<NonNullable<GetRegion200>["site_type"]>(["core", "distributed"]),"status": faker.helpers.arrayElement<NonNullable<GetRegion200>["status"]>(["ok", "outage"])},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createGetRegionError(data?: Partial<GetRegionError>): GetRegionError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createGetRegionQueryResponse(data?: Partial<GetRegionQueryResponse>): GetRegionQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetRegion200()])
}