/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetIpsQueryParams, GetIps200, GetIpsError, GetIpsQueryResponse } from "../types/GetIps.ts";
import { faker } from "@faker-js/faker";

export function createGetIpsQueryParams(data?: Partial<GetIpsQueryParams>): GetIpsQueryParams {
  
  return {
  ...{"skip_ipv6_rdns": faker.datatype.boolean()},
  ...data || {}
  }
}

/**
 * @description A paginated list of IP Addresses.
 */
export function createGetIps200(data?: Partial<GetIps200>): GetIps200 {
  
  return Object.assign({}, {"page": faker.number.int(),"pages": faker.number.int(),"results": faker.number.int(),"data": faker.helpers.multiple(() => ({"address": faker.string.alpha(),"gateway": faker.string.alpha(),"interface_id": faker.number.int(),"linode_id": faker.number.int(),"prefix": faker.number.int(),"public": faker.datatype.boolean(),"rdns": faker.string.alpha(),"region": faker.string.alpha(),"subnet_mask": faker.string.alpha(),"type": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<GetIps200>["data"]>[number]>["type"]>(["ipv4", "ipv6", "ipv6/pool", "ipv6/range"]),"vpc_nat_1_1": {"address": faker.internet.url(),"subnet_id": faker.number.int(),"vpc_id": faker.number.int()}}))})
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createGetIpsError(data?: Partial<GetIpsError>): GetIpsError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createGetIpsQueryResponse(data?: Partial<GetIpsQueryResponse>): GetIpsQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetIps200()])
}