/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PutDiskPathParams, PutDisk200, PutDiskError, PutDiskMutationRequest, PutDiskMutationResponse } from "../types/PutDisk.ts";
import { faker } from "@faker-js/faker";

export function createPutDiskPathParams(data?: Partial<PutDiskPathParams>): PutDiskPathParams {
  
  return {
  ...{"linodeId": faker.number.int(),"diskId": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description The updated Disk.
 */
export function createPutDisk200(data?: Partial<PutDisk200>): PutDisk200 {
  
  return {
  ...{"created": faker.date.anytime().toISOString(),"disk_encryption": faker.string.alpha(),"filesystem": faker.helpers.arrayElement<NonNullable<PutDisk200>["filesystem"]>(["raw", "swap", "ext2", "ext3", "ext4", "initrd"]),"id": faker.number.int(),"label": faker.string.alpha({ length: { min: 1, max: 48 } }),"size": faker.number.int(),"status": faker.helpers.arrayElement<NonNullable<PutDisk200>["status"]>(["ready", "not ready", "deleting"]),"updated": faker.date.anytime().toISOString()},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createPutDiskError(data?: Partial<PutDiskError>): PutDiskError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

/**
 * @description Updates the parameters of a single Disk.
 */
export function createPutDiskMutationRequest(data?: Partial<PutDiskMutationRequest>): PutDiskMutationRequest {
  
  return {
  ...{"label": faker.string.alpha({ length: { min: 1, max: 48 } })},
  ...data || {}
  }
}

export function createPutDiskMutationResponse(data?: Partial<PutDiskMutationResponse>): PutDiskMutationResponse {
  
  return data || faker.helpers.arrayElement<any>([createPutDisk200()])
}