/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetLkeClusterApiEndpointsPathParams, GetLkeClusterApiEndpoints200, GetLkeClusterApiEndpointsError, GetLkeClusterApiEndpointsQueryResponse } from "../types/GetLkeClusterApiEndpoints.ts";
import { faker } from "@faker-js/faker";

export function createGetLkeClusterApiEndpointsPathParams(data?: Partial<GetLkeClusterApiEndpointsPathParams>): GetLkeClusterApiEndpointsPathParams {
  
  return {
  ...{"clusterId": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description Returns the Kubernetes API server endpoints for this cluster.
 */
export function createGetLkeClusterApiEndpoints200(data?: Partial<GetLkeClusterApiEndpoints200>): GetLkeClusterApiEndpoints200 {
  
  return {
  ...{"data": faker.helpers.multiple(() => ({"endpoint": faker.string.alpha()})),"page": faker.number.int(),"pages": faker.number.int(),"results": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createGetLkeClusterApiEndpointsError(data?: Partial<GetLkeClusterApiEndpointsError>): GetLkeClusterApiEndpointsError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createGetLkeClusterApiEndpointsQueryResponse(data?: Partial<GetLkeClusterApiEndpointsQueryResponse>): GetLkeClusterApiEndpointsQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetLkeClusterApiEndpoints200()])
}