/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserType } from "../types/UserType.ts";
import { faker } from "@faker-js/faker";

/**
 * @description The type of user on an account. Mostly applies to the use of the parent and child accounts for Akamai partners functionality.
 */
export function createUserType(data?: Partial<UserType>): UserType {
  
  return {
  ...{"user_type": faker.helpers.arrayElement<NonNullable<UserType>["user_type"]>(["parent", "child", "proxy", "default"])},
  ...data || {}
  }
}