/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const deleteLinodeConfigInterfacePathParamsSchema = z.object({
    "apiVersion": z.enum(["v4", "v4beta"]).describe("__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta."),
"linodeId": z.coerce.number().int().describe("The `id` of the Linode."),
"configId": z.coerce.number().int().describe("The `id` of the Configuration Profile."),
"interfaceId": z.coerce.number().int().describe("The `id` of the Linode Configuration Profile Interface.")
    })

/**
 * @description Configuration profile interface successfully deleted.
 */
export const deleteLinodeConfigInterface200Schema = z.object({
    
    }).describe("The API responds with an empty object.")

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export const deleteLinodeConfigInterfaceErrorSchema = z.object({
    "errors": z.optional(z.array(z.object({
    "field": z.optional(z.string().describe("The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.")),
"reason": z.optional(z.string().describe("What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully."))
    }).describe("An object for describing a single error that occurred during the processing of a request.")))
    })

export const deleteLinodeConfigInterfaceMutationResponseSchema = z.lazy(() => deleteLinodeConfigInterface200Schema)