/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const getDashboardsAllPathParamsSchema = z.object({
    "apiVersion": z.enum(["v4beta"]).describe("__Enum__ Call the `v4beta` URL for operations still only in beta.")
    })

/**
 * @description Returns a paginated list of dashboards.
 */
export const getDashboardsAll200Schema = z.object({
    "data": z.optional(z.array(z.object({
    "created": z.string().datetime().describe("When the dashboard was created."),
"id": z.int().describe("The unique identifier for the dashboard."),
"label": z.string().describe("The name of the dashboard. This is used for display purposes in Akamai Cloud Manager."),
"service_type": z.string().describe("The Akamai Cloud Computing service used by this dashboard."),
"type": z.enum(["standard"]).describe("The type of dashboard. Currently, this can only be `standard` for a dashboard that uses default formatting."),
"updated": z.string().datetime().describe("When the dashboard was last updated."),
"widgets": z.array(z.object({
    "aggregate_function": z.optional(z.enum(["min", "max", "avg", "sum", "rate"]).describe("The aggregate function for the metric. This defaults to `avg` for average.")),
"chart_type": z.optional(z.enum(["line", "area"]).describe("The type of chart used in the widget. This can be `line` for a line chart or `area` for an area chart.")),
"color": z.optional(z.string().describe("The color used in the widget.")),
"label": z.optional(z.string().describe("The name of the widget. This is used for display purposes in Akamai Cloud Manager.")),
"metric": z.optional(z.string().describe("The metric to query.")),
"size": z.optional(z.enum(["6", "12"]).describe("The size of the widget. This can be `6` or `12` grid units, expressed as strings.")),
"unit": z.optional(z.enum(["%", "Bytes", "sec", "bps", "msec", "Bps", "KB", "MB", "GB", "rate", "percentile", "ratio", "OPS", "IOPS"]).describe("The unit of the metric. This can be values like `%` for percentage or `GB` for gigabyte.")),
"y_label": z.optional(z.string().describe("The label for the y-axis in the widget's chart."))
    })).describe("The widgets used in the dashboard.")
    }))),
"page": z.optional(z.int().describe("__Read-only__ The current [page](https://techdocs.akamai.com/linode-api/reference/pagination).")),
"pages": z.optional(z.int().describe("__Read-only__ The total number of [pages](https://techdocs.akamai.com/linode-api/reference/pagination).")),
"results": z.optional(z.int().describe("__Read-only__ The total number of results."))
    })

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export const getDashboardsAllErrorSchema = z.object({
    "errors": z.optional(z.array(z.object({
    "field": z.optional(z.string().describe("The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.")),
"reason": z.optional(z.string().describe("What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully."))
    }).describe("An object for describing a single error that occurred during the processing of a request.")))
    })

export const getDashboardsAllQueryResponseSchema = z.lazy(() => getDashboardsAll200Schema)