/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const getTicketsPathParamsSchema = z.object({
    "apiVersion": z.enum(["v4", "v4beta"]).describe("__Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.")
    })

export const getTicketsQueryParamsSchema = z.object({
    "page": z.coerce.number().int().min(1).default(1).describe("The page of a collection to return."),
"page_size": z.coerce.number().int().min(25).max(500).default(100).describe("The number of items to return per page.")
    })

/**
 * @description Returns a paginated list of support tickets.
 */
export const getTickets200Schema = z.object({
    "data": z.optional(z.array(z.object({
    "attachments": z.optional(z.array(z.string()).describe("__Read-only__ A list of filenames representing attached files associated with this ticket.")),
"closable": z.optional(z.boolean().describe("Whether the ticket can be closed.")),
"closed": z.string().datetime().describe("__Filterable__, __Read-only__ When this ticket was closed.").nullish(),
"description": z.optional(z.string().min(1).max(65000).describe("__Read-only__ The full details of the issue or question.")),
"entity": z.object({
    "id": z.optional(z.int().describe("__Read-only__ The unique ID for this ticket's entity. Empty if the targeted entity doesn't use an `id`.")),
"label": z.optional(z.string().describe("__Read-only__ The current label of this entity.")),
"type": z.optional(z.enum(["database", "domain", "firewall", "linode", "lkecluster", "managed_service", "nodebalancer", "vlan", "volume", "vpc"]).describe("__Read-only__ The type of entity.")),
"url": z.optional(z.string().describe("__Read-only__ The URL where you can access the `entity`. If this is a relative URL, it's relative to the domain for the entity."))
    }).describe("__Read-only__ The ticket was opened for this entity. An entity represents a specific object you've created, such as a Linode or a Managed Database.").nullish(),
"gravatar_id": z.optional(z.string().describe("__Read-only__ The Gravatar ID of the user who opened this ticket.")),
"id": z.optional(z.int().describe("__Read-only__ The ID of the support ticket.")),
"opened": z.optional(z.string().datetime().describe("__Filterable__, __Read-only__ When this ticket was created.")),
"opened_by": z.optional(z.string().describe("__Filterable__, __Read-only__ The user who opened this ticket.")),
"severity": z.enum(["low", "moderate", "major"]).describe("__Read-only__ The severity of this ticket.").nullish(),
"status": z.optional(z.enum(["closed", "new", "open"]).describe("__Filterable__, __Read-only__ The current status of this ticket.")),
"summary": z.optional(z.string().min(1).max(64).describe("__Read-only__ The summary or title for this ticket.")),
"updated": z.optional(z.string().datetime().describe("__Filterable__, __Read-only__ When this ticket was last updated.")),
"updated_by": z.string().describe("__Read-only__ The user who last updated this ticket.").nullish()
    }).describe("A support ticket opened from your account."))),
"page": z.optional(z.int().describe("__Read-only__ The current [page](https://techdocs.akamai.com/linode-api/reference/pagination).")),
"pages": z.optional(z.int().describe("__Read-only__ The total number of [pages](https://techdocs.akamai.com/linode-api/reference/pagination).")),
"results": z.optional(z.int().describe("__Read-only__ The total number of results."))
    })

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export const getTicketsErrorSchema = z.object({
    "errors": z.optional(z.array(z.object({
    "field": z.optional(z.string().describe("The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.")),
"reason": z.optional(z.string().describe("What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully."))
    }).describe("An object for describing a single error that occurred during the processing of a request.")))
    })

export const getTicketsQueryResponseSchema = z.lazy(() => getTickets200Schema)