/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const suspendDatabasesMysqlInstancePathParamsSchema = z.object({
    "apiVersion": z.enum(["v4"]).describe("__Enum__ Call the `v4` URL."),
"instanceId": z.coerce.number().int().describe("The ID of the Managed PostgreSQL Database.")
    })

/**
 * @description MySQL Managed Database successfully suspended.
 */
export const suspendDatabasesMysqlInstance200Schema = z.object({
    
    }).describe("The API responds with an empty object.")

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export const suspendDatabasesMysqlInstanceErrorSchema = z.object({
    "errors": z.optional(z.array(z.object({
    "field": z.optional(z.string().describe("The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.")),
"reason": z.optional(z.string().describe("What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully."))
    }).describe("An object for describing a single error that occurred during the processing of a request.")))
    })

export const suspendDatabasesMysqlInstanceMutationResponseSchema = z.lazy(() => suspendDatabasesMysqlInstance200Schema)