/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Account } from "../types/Account.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Account object.
 */
export function createAccount(data?: Partial<Account>): Account {
  
  return {
  ...{"active_promotions": faker.helpers.multiple(() => ({"credit_monthly_cap": faker.string.alpha(),"credit_remaining": faker.string.alpha(),"description": faker.string.alpha(),"expire_dt": faker.string.alpha(),"image_url": faker.string.alpha(),"service_type": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<Account>["active_promotions"]>[number]>["service_type"]>(["all", "backup", "blockstorage", "db_mysql", "ip_v4", "linode", "linode_disk", "linode_memory", "longview", "managed", "nodebalancer", "objectstorage", "placement_group", "transfer_tx"]),"summary": faker.string.alpha(),"this_month_credit_remaining": faker.string.alpha()})),"active_since": faker.date.anytime().toISOString(),"address_1": faker.string.alpha({ length: 64 }),"address_2": faker.string.alpha({ length: 64 }),"balance": faker.number.float(),"balance_uninvoiced": faker.number.float(),"billing_source": faker.helpers.arrayElement<NonNullable<Account>["billing_source"]>(["akamai", "linode"]),"capabilities": faker.helpers.multiple(() => (faker.string.alpha())),"city": faker.string.alpha({ length: 24 }),"company": faker.string.alpha({ length: 128 }),"country": faker.string.alpha(),"credit_card": {"expiry": faker.string.alpha(),"last_four": faker.string.alpha()},"email": faker.string.alpha({ length: 128 }),"euuid": faker.string.uuid(),"first_name": faker.string.alpha({ length: 50 }),"last_name": faker.string.alpha({ length: 50 }),"phone": faker.string.alpha({ length: 32 }),"state": faker.string.alpha({ length: 24 }),"tax_id": faker.string.alpha({ length: 25 }),"zip": faker.string.alpha()},
  ...data || {}
  }
}