/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PutFirewallRulesPathParams, PutFirewallRules200, PutFirewallRulesError, PutFirewallRulesMutationRequest, PutFirewallRulesMutationResponse } from "../types/PutFirewallRules.ts";
import { faker } from "@faker-js/faker";

export function createPutFirewallRulesPathParams(data?: Partial<PutFirewallRulesPathParams>): PutFirewallRulesPathParams {
  
  return {
  ...{"apiVersion": faker.helpers.arrayElement<NonNullable<PutFirewallRulesPathParams>["apiVersion"]>(["v4", "v4beta"]),"firewallId": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description Firewall Rules updated successfully.
 */
export function createPutFirewallRules200(data?: Partial<PutFirewallRules200>): PutFirewallRules200 {
  
  return {
  ...{"fingerprint": faker.string.alpha(),"inbound": faker.helpers.multiple(() => ({"action": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<PutFirewallRules200>["inbound"]>[number]>["action"]>(["ACCEPT", "DROP"]),"addresses": {"ipv4": faker.helpers.multiple(() => (faker.string.alpha())),"ipv6": faker.helpers.multiple(() => (faker.string.alpha()))},"description": faker.string.alpha({ length: { min: 1, max: 100 } }),"label": faker.string.alpha({ length: { min: 3, max: 32 } }),"ports": faker.string.alpha(),"protocol": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<PutFirewallRules200>["inbound"]>[number]>["protocol"]>(["TCP", "UDP", "ICMP", "IPENCAP"])})),"inbound_policy": faker.helpers.arrayElement<NonNullable<PutFirewallRules200>["inbound_policy"]>(["ACCEPT", "DROP"]),"outbound": faker.helpers.multiple(() => ({"action": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<PutFirewallRules200>["outbound"]>[number]>["action"]>(["ACCEPT", "DROP"]),"addresses": {"ipv4": faker.helpers.multiple(() => (faker.string.alpha())),"ipv6": faker.helpers.multiple(() => (faker.string.alpha()))},"description": faker.string.alpha({ length: { min: 1, max: 100 } }),"label": faker.string.alpha({ length: { min: 3, max: 32 } }),"ports": faker.string.alpha(),"protocol": faker.helpers.arrayElement<NonNullable<NonNullable<NonNullable<PutFirewallRules200>["outbound"]>[number]>["protocol"]>(["TCP", "UDP", "ICMP", "IPENCAP"])})),"outbound_policy": faker.helpers.arrayElement<NonNullable<PutFirewallRules200>["outbound_policy"]>(["ACCEPT", "DROP"]),"version": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createPutFirewallRulesError(data?: Partial<PutFirewallRulesError>): PutFirewallRulesError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

/**
 * @description The Firewall Rules information to update.
 */
export function createPutFirewallRulesMutationRequest(data?: Partial<PutFirewallRulesMutationRequest>): PutFirewallRulesMutationRequest {
  
  return Object.assign({}, {"fingerprint": faker.string.alpha(),"inbound": undefined,"inbound_policy": faker.helpers.arrayElement<NonNullable<PutFirewallRulesMutationRequest>["inbound_policy"]>(["ACCEPT", "DROP"]),"outbound": undefined,"outbound_policy": faker.helpers.arrayElement<NonNullable<PutFirewallRulesMutationRequest>["outbound_policy"]>(["ACCEPT", "DROP"]),"version": faker.number.int()})
}

export function createPutFirewallRulesMutationResponse(data?: Partial<PutFirewallRulesMutationResponse>): PutFirewallRulesMutationResponse {
  
  return data || faker.helpers.arrayElement<any>([createPutFirewallRules200()])
}