/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetLkeClusterPathParams, GetLkeCluster200, GetLkeClusterError, GetLkeClusterQueryResponse } from "../types/GetLkeCluster.ts";
import { faker } from "@faker-js/faker";

export function createGetLkeClusterPathParams(data?: Partial<GetLkeClusterPathParams>): GetLkeClusterPathParams {
  
  return {
  ...{"apiVersion": faker.helpers.arrayElement<NonNullable<GetLkeClusterPathParams>["apiVersion"]>(["v4", "v4beta"]),"clusterId": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description Returns a single Kubernetes cluster.
 */
export function createGetLkeCluster200(data?: Partial<GetLkeCluster200>): GetLkeCluster200 {
  
  return {
  ...{"apl_enabled": faker.datatype.boolean(),"control_plane": {"audit_logs_enabled": faker.datatype.boolean(),"high_availability": faker.datatype.boolean()},"created": faker.date.anytime().toISOString(),"id": faker.number.int(),"k8s_version": faker.string.alpha(),"label": faker.string.alpha({ length: { min: 1, max: 32 } }),"region": faker.string.alpha(),"stack_type": faker.helpers.arrayElement<NonNullable<GetLkeCluster200>["stack_type"]>(["ipv4", "ipv4-ipv6"]),"subnet_id": faker.number.int(),"tags": faker.helpers.multiple(() => (faker.string.alpha())),"tier": faker.helpers.arrayElement<NonNullable<GetLkeCluster200>["tier"]>(["standard", "enterprise"]),"updated": faker.date.anytime().toISOString(),"vpc_id": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createGetLkeClusterError(data?: Partial<GetLkeClusterError>): GetLkeClusterError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createGetLkeClusterQueryResponse(data?: Partial<GetLkeClusterQueryResponse>): GetLkeClusterQueryResponse {
  
  return data || faker.helpers.arrayElement<any>([createGetLkeCluster200()])
}