/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostResetLinodePasswordPathParams, PostResetLinodePassword200, PostResetLinodePasswordError, PostResetLinodePasswordMutationRequest, PostResetLinodePasswordMutationResponse } from "../types/PostResetLinodePassword.ts";
import { faker } from "@faker-js/faker";

export function createPostResetLinodePasswordPathParams(data?: Partial<PostResetLinodePasswordPathParams>): PostResetLinodePasswordPathParams {
  
  return {
  ...{"apiVersion": faker.helpers.arrayElement<NonNullable<PostResetLinodePasswordPathParams>["apiVersion"]>(["v4", "v4beta"]),"linodeId": faker.number.int()},
  ...data || {}
  }
}

/**
 * @description Password Reset.
 */
export function createPostResetLinodePassword200(data?: Partial<PostResetLinodePassword200>): PostResetLinodePassword200 {
  
  return {
  ...{},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createPostResetLinodePasswordError(data?: Partial<PostResetLinodePasswordError>): PostResetLinodePasswordError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

/**
 * @description This Linode\'s new root password.
 */
export function createPostResetLinodePasswordMutationRequest(data?: Partial<PostResetLinodePasswordMutationRequest>): PostResetLinodePasswordMutationRequest {
  
  return {
  ...{"root_pass": faker.string.alpha()},
  ...data || {}
  }
}

export function createPostResetLinodePasswordMutationResponse(data?: Partial<PostResetLinodePasswordMutationResponse>): PostResetLinodePasswordMutationResponse {
  
  return data || faker.helpers.arrayElement<any>([createPostResetLinodePassword200()])
}