/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AddedPostPayment } from "../types/AddedPostPayment.ts";
import { faker } from "@faker-js/faker";

export function createAddedPostPayment(data?: Partial<AddedPostPayment>): AddedPostPayment {
  
  return {
  ...{"payment_method_id": faker.number.int(),"usd": faker.helpers.fromRegExp("^\$?\d+\.\d{2}$")},
  ...data || {}
  }
}