/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ErrorResponse } from "../types/ErrorResponse.ts";
import { faker } from "@faker-js/faker";

export function createErrorResponse(data?: Partial<ErrorResponse>): ErrorResponse {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}