/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostPayPalPaymentPathParams, PostPayPalPayment200, PostPayPalPayment299, PostPayPalPaymentError, PostPayPalPaymentMutationRequest, PostPayPalPaymentMutationResponse } from "../types/PostPayPalPayment.ts";
import { faker } from "@faker-js/faker";

export function createPostPayPalPaymentPathParams(data?: Partial<PostPayPalPaymentPathParams>): PostPayPalPaymentPathParams {
  
  return {
  ...{"apiVersion": faker.helpers.arrayElement<NonNullable<PostPayPalPaymentPathParams>["apiVersion"]>(["v4", "v4beta"])},
  ...data || {}
  }
}

/**
 * @description PayPal Payment staged.
 */
export function createPostPayPalPayment200(data?: Partial<PostPayPalPayment200>): PostPayPalPayment200 {
  
  return {
  ...{"checkout_token": faker.string.alpha(),"payment_id": faker.string.alpha()},
  ...data || {}
  }
}

/**
 * @description Request successful. This operation is deprecated and may be removed in a future release.\n\nA warnings array is included with the standard 200 response body.
 */
export function createPostPayPalPayment299(data?: Partial<PostPayPalPayment299>): PostPayPalPayment299 {
  
  return {
  ...{"warnings": faker.helpers.multiple(() => ({"details": faker.string.alpha(),"title": faker.string.alpha()}))},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createPostPayPalPaymentError(data?: Partial<PostPayPalPaymentError>): PostPayPalPaymentError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

/**
 * @description The amount of the Payment to submit via PayPal.
 */
export function createPostPayPalPaymentMutationRequest(data?: Partial<PostPayPalPaymentMutationRequest>): PostPayPalPaymentMutationRequest {
  
  return {
  ...{"cancel_url": faker.string.alpha(),"redirect_url": faker.string.alpha(),"usd": faker.string.alpha()},
  ...data || {}
  }
}

export function createPostPayPalPaymentMutationResponse(data?: Partial<PostPayPalPaymentMutationResponse>): PostPayPalPaymentMutationResponse {
  
  return data || faker.helpers.arrayElement<any>([createPostPayPalPayment200(), createPostPayPalPayment299()])
}