/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostSharegroupsPathParams, PostSharegroups200, PostSharegroupsError, PostSharegroupsMutationRequest, PostSharegroupsMutationResponse } from "../types/PostSharegroups.ts";
import { faker } from "@faker-js/faker";

export function createPostSharegroupsPathParams(data?: Partial<PostSharegroupsPathParams>): PostSharegroupsPathParams {
  
  return {
  ...{"apiVersion": faker.helpers.arrayElement<NonNullable<PostSharegroupsPathParams>["apiVersion"]>(["v4", "v4beta"])},
  ...data || {}
  }
}

/**
 * @description New share group created successfully.
 */
export function createPostSharegroups200(data?: Partial<PostSharegroups200>): PostSharegroups200 {
  
  return {
  ...{"created": faker.date.anytime().toISOString(),"description": faker.string.alpha(),"expiry": faker.date.anytime().toISOString(),"id": faker.number.int(),"images_count": faker.number.int(),"is_suspended": faker.datatype.boolean(),"label": faker.string.alpha(),"members_count": faker.number.int(),"updated": faker.date.anytime().toISOString(),"uuid": faker.string.uuid()},
  ...data || {}
  }
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
 */
export function createPostSharegroupsError(data?: Partial<PostSharegroupsError>): PostSharegroupsError {
  
  return {
  ...{"errors": faker.helpers.multiple(() => ({"field": faker.string.alpha(),"reason": faker.string.alpha()}))},
  ...data || {}
  }
}

export function createPostSharegroupsMutationRequest(data?: Partial<PostSharegroupsMutationRequest>): PostSharegroupsMutationRequest {
  
  return {
  ...{"description": faker.string.alpha(),"images": faker.helpers.multiple(() => ({"description": faker.string.alpha(),"id": faker.string.alpha(),"label": faker.string.alpha()})),"label": faker.string.alpha()},
  ...data || {}
  }
}

export function createPostSharegroupsMutationResponse(data?: Partial<PostSharegroupsMutationResponse>): PostSharegroupsMutationResponse {
  
  return data || faker.helpers.arrayElement<any>([createPostSharegroups200()])
}