/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AddedPostEntityTransfer {
    /**
     * @description A collection of the entities to include in this transfer request, separated by type.
     * @type object
    */
    entities: {
        /**
         * @description An array containing the IDs of each of the Linodes included in this transfer.
         * @type array | undefined
        */
        linodes?: number[];
    };
}