/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AddedGetAvailability200 {
    /**
     * @type array | undefined
    */
    data?: {
        /**
         * @description __Read-only__ A list of services _available_ to your account in the `region`.
         * @type array | undefined
        */
        readonly available?: string[];
        /**
         * @description __Read-only__ The Akamai cloud computing data center (region), represented by a slug value. You can view a full list of regions and their associated slugs with the [List regions](https://techdocs.akamai.com/linode-api/reference/get-regions) operation.
         * @type string | undefined
        */
        readonly region?: string;
        /**
         * @description __Read-only__ A list of services _unavailable_ to your account in the `region`.
         * @type array | undefined
        */
        readonly unavailable?: string[];
    }[];
    /**
     * @description __Read-only__ The current [page](https://techdocs.akamai.com/linode-api/reference/pagination).
     * @type integer | undefined
    */
    readonly page?: number;
    /**
     * @description __Read-only__ The total number of [pages](https://techdocs.akamai.com/linode-api/reference/pagination).
     * @type integer | undefined
    */
    readonly pages?: number;
    /**
     * @description __Read-only__ The total number of results.
     * @type integer | undefined
    */
    readonly results?: number;
}