/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AddedPostCancelAccount504 {
    /**
     * @type array | undefined
    */
    errors?: {
        /**
         * @description A string explaining that the account is taking longer to close than expected.
         * @type string | undefined
        */
        reason?: string;
    }[];
}