/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description An object representing the credit card information you have on file with Linode to make Payments against your Account.
*/
export interface CreditCard {
    /**
     * @description Your credit card number. No spaces or hyphens (`-`) allowed.
     * @minLength 14
     * @maxLength 24
     * @type string, digits
    */
    card_number: string;
    /**
     * @description CVV (Card Verification Value) of the credit card, typically found on the back of the card.
     * @minLength 3
     * @maxLength 4
     * @type string, digits
    */
    cvv: string;
    /**
     * @description A value from 1-12 representing the expiration month of your credit card.\n\n  - 1 = January\n  - 2 = February\n  - 3 = March\n  - Etc.
     * @minLength 1
     * @maxLength 12
     * @type integer
    */
    expiry_month: number;
    /**
     * @description A four-digit integer representing the expiration year of your credit card.\n\nThe combination of `expiry_month` and `expiry_year` must result in a month/year combination of the current month or in the future. An expiration date set in the past is invalid.
     * @minLength 4
     * @maxLength 4
     * @type integer
    */
    expiry_year: number;
}