/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const getFirewallDevicesPathParamsApiVersionEnum = {
    "v4": "v4",
    "v4beta": "v4beta"
} as const;

export type GetFirewallDevicesPathParamsApiVersionEnumKey = (typeof getFirewallDevicesPathParamsApiVersionEnum)[keyof typeof getFirewallDevicesPathParamsApiVersionEnum];

export interface GetFirewallDevicesPathParams {
    /**
     * @description __Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.
     * @type string
    */
    apiVersion: GetFirewallDevicesPathParamsApiVersionEnumKey;
    /**
     * @description ID of the Firewall to access.
     * @type integer
    */
    firewallId: number;
}

export interface GetFirewallDevicesQueryParams {
    /**
     * @description The page of a collection to return.
     * @minLength 1
     * @default 1
     * @type integer | undefined
    */
    page?: number;
    /**
     * @description The number of items to return per page.
     * @minLength 25
     * @maxLength 500
     * @default 100
     * @type integer | undefined
    */
    page_size?: number;
}

export const parentEntityTypeEnum11 = {
    "linode": "linode"
} as const;

export type ParentEntityTypeEnum11Key = (typeof parentEntityTypeEnum11)[keyof typeof parentEntityTypeEnum11];

export const entityTypeEnum11 = {
    "linode": "linode",
    "nodebalancer": "nodebalancer",
    "linode_interface": "linode_interface"
} as const;

export type EntityTypeEnum11Key = (typeof entityTypeEnum11)[keyof typeof entityTypeEnum11];

/**
 * @description A paginated list of Firewall Devices.
*/
export interface GetFirewallDevices200 {
    /**
     * @type array | undefined
    */
    data?: {
        /**
         * @description __Filterable__, __Read-only__ When this device was created.
         * @type string | undefined, date-time
        */
        readonly created?: string;
        /**
         * @description The Linode, NodeBalancer, or Linode interface this firewall is assigned to.
         * @type object | undefined
        */
        entity?: {
            /**
             * @description The entity\'s ID.
             * @type integer | undefined
            */
            id?: number;
            /**
             * @description __Read-only__ The entity\'s label.
             * @type string | undefined
            */
            readonly label?: string;
            /**
             * @description __Read-only__ The Linode this `linode_interface` is assigned to. Returns `null` when the entity `type` is `linode` or `nodebalancer`.
             * @type object
            */
            readonly parent_entity?: {
                /**
                 * @description The ID of the Linode assigned to this `linode_interface`.
                 * @type integer | undefined
                */
                id?: number;
                /**
                 * @description The name of the Linode this `linode_interface` is assigned to.
                 * @type string | undefined
                */
                label?: string;
                /**
                 * @description __Read-only__ Currently, no parent entity has a parent of its own. Each `parent_entity` will have its own `parent_entity` set to `null`.
                 * @type string
                */
                readonly parent_entity?: string | null;
                /**
                 * @description A Linode interface’s `parent_entity` is a Linode.
                 * @type string | undefined
                */
                type?: ParentEntityTypeEnum11Key;
                /**
                 * @description The API URL path you can use to access this entity.
                 * @type string | undefined, url
                */
                url?: string;
            } | null;
            /**
             * @description The entity\'s type.
             * @type string | undefined
            */
            type?: EntityTypeEnum11Key;
            /**
             * @description __Read-only__ The API URL path you can use to access this entity.
             * @type string | undefined, url
            */
            readonly url?: string;
        };
        /**
         * @description __Filterable__ The device\'s unique ID.
         * @type integer | undefined
        */
        id?: number;
        /**
         * @description __Filterable__, __Read-only__ When this device was last updated.
         * @type string | undefined, date-time
        */
        readonly updated?: string;
    }[];
    /**
     * @description __Read-only__ The current [page](https://techdocs.akamai.com/linode-api/reference/pagination).
     * @type integer | undefined
    */
    readonly page?: number;
    /**
     * @description __Read-only__ The total number of [pages](https://techdocs.akamai.com/linode-api/reference/pagination).
     * @type integer | undefined
    */
    readonly pages?: number;
    /**
     * @description __Read-only__ The total number of results.
     * @type integer | undefined
    */
    readonly results?: number;
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface GetFirewallDevicesError {
    /**
     * @type array | undefined
    */
    errors?: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string | undefined
        */
        field?: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string | undefined
        */
        reason?: string;
    }[];
}

export type GetFirewallDevicesQueryResponse = GetFirewallDevices200;

export type GetFirewallDevicesQuery = {
    Response: GetFirewallDevices200;
    PathParams: GetFirewallDevicesPathParams;
    QueryParams: GetFirewallDevicesQueryParams;
    Errors: any;
};