/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const getLkeClusterApiEndpointsPathParamsApiVersionEnum = {
    "v4": "v4",
    "v4beta": "v4beta"
} as const;

export type GetLkeClusterApiEndpointsPathParamsApiVersionEnumKey = (typeof getLkeClusterApiEndpointsPathParamsApiVersionEnum)[keyof typeof getLkeClusterApiEndpointsPathParamsApiVersionEnum];

export interface GetLkeClusterApiEndpointsPathParams {
    /**
     * @description __Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.
     * @type string
    */
    apiVersion: GetLkeClusterApiEndpointsPathParamsApiVersionEnumKey;
    /**
     * @description ID of the Kubernetes cluster to look up.
     * @type integer
    */
    clusterId: number;
}

/**
 * @description Returns the Kubernetes API server endpoints for this cluster.
*/
export interface GetLkeClusterApiEndpoints200 {
    /**
     * @description The Kubernetes API server endpoints for this cluster.
     * @type array | undefined
    */
    data?: {
        /**
         * @description __Read-only__ A Kubernetes API server endpoint for this cluster.
         * @type string | undefined
        */
        readonly endpoint?: string;
    }[];
    /**
     * @description __Read-only__ The current [page](https://techdocs.akamai.com/linode-api/reference/pagination).
     * @type integer | undefined
    */
    readonly page?: number;
    /**
     * @description __Read-only__ The total number of [pages](https://techdocs.akamai.com/linode-api/reference/pagination).
     * @type integer | undefined
    */
    readonly pages?: number;
    /**
     * @description __Read-only__ The total number of results.
     * @type integer | undefined
    */
    readonly results?: number;
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface GetLkeClusterApiEndpointsError {
    /**
     * @type array | undefined
    */
    errors?: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string | undefined
        */
        field?: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string | undefined
        */
        reason?: string;
    }[];
}

export type GetLkeClusterApiEndpointsQueryResponse = GetLkeClusterApiEndpoints200;

export type GetLkeClusterApiEndpointsQuery = {
    Response: GetLkeClusterApiEndpoints200;
    PathParams: GetLkeClusterApiEndpointsPathParams;
    Errors: any;
};