/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const getLinodeConfigInterfacesPathParamsApiVersionEnum = {
    "v4": "v4",
    "v4beta": "v4beta"
} as const;

export type GetLinodeConfigInterfacesPathParamsApiVersionEnumKey = (typeof getLinodeConfigInterfacesPathParamsApiVersionEnum)[keyof typeof getLinodeConfigInterfacesPathParamsApiVersionEnum];

export interface GetLinodeConfigInterfacesPathParams {
    /**
     * @description __Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.
     * @type string
    */
    apiVersion: GetLinodeConfigInterfacesPathParamsApiVersionEnumKey;
    /**
     * @description The `id` of the Linode.
     * @type integer
    */
    linodeId: number;
    /**
     * @description The `id` of the Configuration Profile.
     * @type integer
    */
    configId: number;
}

export const ipv4Nat11Enum10 = {
    "any": "any"
} as const;

export type Ipv4Nat11Enum10Key = (typeof ipv4Nat11Enum10)[keyof typeof ipv4Nat11Enum10];

export const getLinodeConfigInterfaces200PurposeEnum = {
    "public": "public",
    "vlan": "vlan",
    "vpc": "vpc"
} as const;

export type GetLinodeConfigInterfaces200PurposeEnumKey = (typeof getLinodeConfigInterfaces200PurposeEnum)[keyof typeof getLinodeConfigInterfaces200PurposeEnum];

/**
 * @description An ordered array of configuration profile interface objects.
 * @example [object Object],[object Object],[object Object]
*/
export type GetLinodeConfigInterfaces200 = Ipv4Nat11Enum10Key[];

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface GetLinodeConfigInterfacesError {
    /**
     * @type array | undefined
    */
    errors?: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string | undefined
        */
        field?: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string | undefined
        */
        reason?: string;
    }[];
}

export type GetLinodeConfigInterfacesQueryResponse = GetLinodeConfigInterfaces200;

export type GetLinodeConfigInterfacesQuery = {
    Response: GetLinodeConfigInterfaces200;
    PathParams: GetLinodeConfigInterfacesPathParams;
    Errors: any;
};