/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const getRegionAvailabilityPathParamsApiVersionEnum = {
    "v4": "v4",
    "v4beta": "v4beta"
} as const;

export type GetRegionAvailabilityPathParamsApiVersionEnumKey = (typeof getRegionAvailabilityPathParamsApiVersionEnum)[keyof typeof getRegionAvailabilityPathParamsApiVersionEnum];

export interface GetRegionAvailabilityPathParams {
    /**
     * @description __Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.
     * @type string
    */
    apiVersion: GetRegionAvailabilityPathParamsApiVersionEnumKey;
    /**
     * @description The abbreviated value (\"slug\") for the applicable data center. Run the [List regions](https://techdocs.akamai.com/linode-api/reference/get-regions) operation to view the slug for each data center.
     * @type string
    */
    regionId: string;
}

/**
 * @description The availability data for a single Region.
*/
export type GetRegionAvailability200 = {
    /**
     * @description __Filterable__ Whether the compute instance type is available in the region.
     * @type boolean | undefined
    */
    available?: boolean;
    /**
     * @description __Filterable__ The compute instance [Type](https://techdocs.akamai.com/linode-api/reference/get-linode-types) ID.
     * @type string | undefined
    */
    plan?: string;
    /**
     * @description __Filterable__ The [Region](https://techdocs.akamai.com/linode-api/reference/get-regions) ID.
     * @type string | undefined
    */
    region?: string;
}[];

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface GetRegionAvailabilityError {
    /**
     * @type array | undefined
    */
    errors?: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string | undefined
        */
        field?: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string | undefined
        */
        reason?: string;
    }[];
}

export type GetRegionAvailabilityQueryResponse = GetRegionAvailability200;

export type GetRegionAvailabilityQuery = {
    Response: GetRegionAvailability200;
    PathParams: GetRegionAvailabilityPathParams;
    Errors: any;
};