/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const getTicketPathParamsApiVersionEnum = {
    "v4": "v4",
    "v4beta": "v4beta"
} as const;

export type GetTicketPathParamsApiVersionEnumKey = (typeof getTicketPathParamsApiVersionEnum)[keyof typeof getTicketPathParamsApiVersionEnum];

export interface GetTicketPathParams {
    /**
     * @description __Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.
     * @type string
    */
    apiVersion: GetTicketPathParamsApiVersionEnumKey;
    /**
     * @description The ID of the support ticket.
     * @type integer
    */
    ticketId: number;
}

export const entityTypeEnum15 = {
    "database": "database",
    "domain": "domain",
    "firewall": "firewall",
    "linode": "linode",
    "lkecluster": "lkecluster",
    "managed_service": "managed_service",
    "nodebalancer": "nodebalancer",
    "vlan": "vlan",
    "volume": "volume",
    "vpc": "vpc"
} as const;

export type EntityTypeEnum15Key = (typeof entityTypeEnum15)[keyof typeof entityTypeEnum15];

export const getTicket200SeverityEnum = {
    "low": "low",
    "moderate": "moderate",
    "major": "major"
} as const;

export type GetTicket200SeverityEnumKey = (typeof getTicket200SeverityEnum)[keyof typeof getTicket200SeverityEnum];

export const getTicket200StatusEnum = {
    "closed": "closed",
    "new": "new",
    "open": "open"
} as const;

export type GetTicket200StatusEnumKey = (typeof getTicket200StatusEnum)[keyof typeof getTicket200StatusEnum];

/**
 * @description Returns a single support ticket.
*/
export interface GetTicket200 {
    /**
     * @description __Read-only__ A list of filenames representing attached files associated with this ticket.
     * @type array | undefined
    */
    readonly attachments?: string[];
    /**
     * @description Whether the ticket can be closed.
     * @type boolean | undefined
    */
    closable?: boolean;
    /**
     * @description __Filterable__, __Read-only__ When this ticket was closed.
     * @type string, date-time
    */
    readonly closed?: string | null;
    /**
     * @description __Read-only__ The full details of the issue or question.
     * @minLength 1
     * @maxLength 65000
     * @type string | undefined
    */
    readonly description?: string;
    /**
     * @description __Read-only__ The ticket was opened for this entity. An entity represents a specific object you\'ve created, such as a Linode or a Managed Database.
     * @type object
    */
    readonly entity?: {
        /**
         * @description __Read-only__ The unique ID for this ticket\'s entity. Empty if the targeted entity doesn\'t use an `id`.
         * @type integer | undefined
        */
        readonly id?: number;
        /**
         * @description __Read-only__ The current label of this entity.
         * @type string | undefined
        */
        readonly label?: string;
        /**
         * @description __Read-only__ The type of entity.
         * @type string | undefined
        */
        readonly type?: EntityTypeEnum15Key;
        /**
         * @description __Read-only__ The URL where you can access the `entity`. If this is a relative URL, it\'s relative to the domain for the entity.
         * @type string | undefined
        */
        readonly url?: string;
    } | null;
    /**
     * @description __Read-only__ The Gravatar ID of the user who opened this ticket.
     * @type string | undefined
    */
    readonly gravatar_id?: string;
    /**
     * @description __Read-only__ The ID of the support ticket.
     * @type integer | undefined
    */
    readonly id?: number;
    /**
     * @description __Filterable__, __Read-only__ When this ticket was created.
     * @type string | undefined, date-time
    */
    readonly opened?: string;
    /**
     * @description __Filterable__, __Read-only__ The user who opened this ticket.
     * @type string | undefined
    */
    readonly opened_by?: string;
    /**
     * @description __Read-only__ The severity of this ticket.
     * @type string
    */
    readonly severity?: GetTicket200SeverityEnumKey | null;
    /**
     * @description __Filterable__, __Read-only__ The current status of this ticket.
     * @type string | undefined
    */
    readonly status?: GetTicket200StatusEnumKey;
    /**
     * @description __Read-only__ The summary or title for this ticket.
     * @minLength 1
     * @maxLength 64
     * @type string | undefined
    */
    readonly summary?: string;
    /**
     * @description __Filterable__, __Read-only__ When this ticket was last updated.
     * @type string | undefined, date-time
    */
    readonly updated?: string;
    /**
     * @description __Read-only__ The user who last updated this ticket.
     * @type string
    */
    readonly updated_by?: string | null;
}

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface GetTicketError {
    /**
     * @type array | undefined
    */
    errors?: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string | undefined
        */
        field?: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string | undefined
        */
        reason?: string;
    }[];
}

export type GetTicketQueryResponse = GetTicket200;

export type GetTicketQuery = {
    Response: GetTicket200;
    PathParams: GetTicketPathParams;
    Errors: any;
};