/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description An object representing an execution of Payment to PayPal to capture the funds and credit your Linode Account.
*/
export interface PaypalExecute {
    /**
     * @description The PayerID returned by PayPal during the transaction authorization process.
     * @type string
    */
    payer_id: string;
    /**
     * @description The PaymentID returned from [Stage a PayPal payment](https://techdocs.akamai.com/linode-api/reference/post-pay-pal-payment) that has been approved with PayPal.
     * @type string
    */
    payment_id: string;
}