/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const postAssignIpsPathParamsApiVersionEnum = {
    "v4": "v4",
    "v4beta": "v4beta"
} as const;

export type PostAssignIpsPathParamsApiVersionEnumKey = (typeof postAssignIpsPathParamsApiVersionEnum)[keyof typeof postAssignIpsPathParamsApiVersionEnum];

export interface PostAssignIpsPathParams {
    /**
     * @description __Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.
     * @type string
    */
    apiVersion: PostAssignIpsPathParamsApiVersionEnumKey;
}

/**
 * @description All assignments completed successfully.
*/
export type PostAssignIps200 = object;

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface PostAssignIpsError {
    /**
     * @type array | undefined
    */
    errors?: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string | undefined
        */
        field?: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string | undefined
        */
        reason?: string;
    }[];
}

/**
 * @description Information about what IPv4 address or IPv6 range to assign, and to which Linode.
*/
export interface PostAssignIpsMutationRequest {
    /**
     * @description The list of assignments to make. You must have read_write access to all IPs being assigned and all Linodes being assigned to in order for the assignments to succeed.
     * @type array
    */
    assignments: {
        /**
         * @description The IPv4 address or IPv6 range for this assignment.\n\n- Must be an IPv4 address or an IPv6 range you can access in the Region specified.\n- IPv6 ranges must include a prefix length of `/56` or `/64`, for example: `2001:db8:3c4d:15::/64`.\n- Assignment of an IPv6 range to a Linode updates the route target of the range to the assigned Linode\'s SLAAC address.\n- Can be a public or private address.\n- For Linode interfaces, public IPv4 addresses or public IPv6 ranges can be exchanged on public interfaces. Private IPv4 addresses are not supported.
         * @type string, ipv4|ipv6/prefix_length
        */
        address: string;
        /**
         * @description The ID of the Linode to assign this address to. The IP\'s previous Linode will lose this address, and must end up with at least one public address and no more than one private address once all assignments have been made.
         * @type integer
        */
        linode_id: number;
    }[];
    /**
     * @description The ID of the Region in which these assignments are to take place. All IPs and Linodes must exist in this Region.
     * @type string
    */
    region: string;
}

export type PostAssignIpsMutationResponse = PostAssignIps200;

export type PostAssignIpsMutation = {
    Response: PostAssignIps200;
    Request: PostAssignIpsMutationRequest;
    PathParams: PostAssignIpsPathParams;
    Errors: any;
};