/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const postApplyFirewallsPathParamsApiVersionEnum = {
    "v4": "v4",
    "v4beta": "v4beta"
} as const;

export type PostApplyFirewallsPathParamsApiVersionEnumKey = (typeof postApplyFirewallsPathParamsApiVersionEnum)[keyof typeof postApplyFirewallsPathParamsApiVersionEnum];

export interface PostApplyFirewallsPathParams {
    /**
     * @description __Enum__ Call either the `v4` URL, or `v4beta` for operations still in Beta.
     * @type string
    */
    apiVersion: PostApplyFirewallsPathParamsApiVersionEnumKey;
    /**
     * @description The ID of the Linode.
     * @type integer
    */
    linodeId: number;
}

/**
 * @description Applying firewalls started.
*/
export type PostApplyFirewalls200 = object;

/**
 * @description See [Errors](https://techdocs.akamai.com/linode-api/reference/errors) for the range of possible error response codes.
*/
export interface PostApplyFirewallsError {
    /**
     * @type array | undefined
    */
    errors?: {
        /**
         * @description The field in the request that caused this error. This may be a path, separated by periods in the case of nested fields. In some cases this may come back as `null` if the error is not specific to any single element of the request.
         * @type string | undefined
        */
        field?: string;
        /**
         * @description What happened to cause this error. In most cases, this can be fixed immediately by changing the data you sent in the request, but in some cases you will be instructed to [Open a support ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket) or perform some other action before you can complete the request successfully.
         * @type string | undefined
        */
        reason?: string;
    }[];
}

export type PostApplyFirewallsMutationResponse = PostApplyFirewalls200;

export type PostApplyFirewallsMutation = {
    Response: PostApplyFirewalls200;
    PathParams: PostApplyFirewallsPathParams;
    Errors: any;
};