/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/fetch.ts";
import type { DeleteNodeBalancerMutationResponse, DeleteNodeBalancerPathParams } from "../types/DeleteNodeBalancer.ts";
import { fetch } from "../.kubb/fetch.ts";

function getDeleteNodeBalancerUrl(nodeBalancerId: DeleteNodeBalancerPathParams["nodeBalancerId"]) {
  const res = { method: 'DELETE', url: `/nodebalancers/${nodeBalancerId}` as const }  
  return res
}

/**
 * @description Deletes a NodeBalancer.__This is a destructive action and cannot be undone.__Deleting a NodeBalancer will also delete all associated Configs and Nodes, although the backend servers represented by the Nodes will not be changed or removed. Deleting a NodeBalancer will cause you to lose access to the IP Addresses assigned to this NodeBalancer.<<LB>>---- __CLI__.    ```    linode-cli nodebalancers delete 12345    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    nodebalancers:read_write    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Delete a NodeBalancer
 * {@link /nodebalancers/:nodeBalancerId}
 */
export async function deleteNodeBalancer(nodeBalancerId: DeleteNodeBalancerPathParams["nodeBalancerId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteNodeBalancerMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteNodeBalancerUrl(nodeBalancerId).url.toString(), ... requestConfig })  
  return res.data
}