/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetAccountQueryResponse, GetAccountPathParams } from "../types/GetAccount.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetAccountUrl(apiVersion: GetAccountPathParams["apiVersion"]) {
  const res = { method: 'GET', url: `/${apiVersion}/account` as const }  
  return res
}

/**
 * @description Returns the contact and billing information related to your account.<<LB>>---- __CLI__.    ```    linode-cli account view    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    account:read_only    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Get your account
 * {@link /:apiVersion/account}
 */
export async function getAccount(apiVersion: GetAccountPathParams["apiVersion"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetAccountQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetAccountUrl(apiVersion).url.toString(), ... requestConfig })  
  return res.data
}