/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetAvailabilityQueryResponse, GetAvailabilityPathParams, GetAvailabilityQueryParams } from "../types/GetAvailability.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetAvailabilityUrl(apiVersion: GetAvailabilityPathParams["apiVersion"]) {
  const res = { method: 'GET', url: `/${apiVersion}/account/availability` as const }  
  return res
}

/**
 * @description Returns a paginated list of the services available to you, for all Linode regions.> 📘>> Only authorized users can run this operation.<<LB>>---- __CLI__.    ```    linode-cli account get-availability    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    account:read_only    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary List available services
 * {@link /:apiVersion/account/availability}
 */
export async function getAvailability(apiVersion: GetAvailabilityPathParams["apiVersion"], params?: GetAvailabilityQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetAvailabilityQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetAvailabilityUrl(apiVersion).url.toString(), params, ... requestConfig })  
  return res.data
}