/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/fetch.ts";
import type { GetEventsQueryResponse, GetEventsQueryParams, GetEventsHeaderParams } from "../types/GetEvents.ts";
import { fetch } from "../.kubb/fetch.ts";

function getGetEventsUrl() {
  const res = { method: 'GET', url: `/account/events` as const }  
  return res
}

/**
 * @description Returns a collection of event objects that represent actions you've taken on your account, over the last 90 days. The events returned depend on your user grants.<<LB>>---- __CLI__.    ```    linode-cli events list    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    events:read_only    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary List events
 * {@link /account/events}
 */
export async function getEvents(params?: GetEventsQueryParams, headers?: GetEventsHeaderParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetEventsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetEventsUrl().url.toString(), params, ... requestConfig, headers : { ...headers, ...requestConfig.headers } })  
  return res.data
}