/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetLkeClustersQueryResponse, GetLkeClustersPathParams } from "../types/GetLkeClusters.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetLkeClustersUrl(apiVersion: GetLkeClustersPathParams["apiVersion"]) {
  const res = { method: 'GET', url: `/${apiVersion}/lke/clusters` as const }  
  return res
}

/**
 * @description Lists current Kubernetes clusters available on your account.<<LB>>---- __CLI__.    ```    linode-cli lke clusters-list    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    lke:read_only    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary List Kubernetes clusters
 * {@link /:apiVersion/lke/clusters}
 */
export async function getLkeClusters(apiVersion: GetLkeClustersPathParams["apiVersion"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetLkeClustersQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetLkeClustersUrl(apiVersion).url.toString(), ... requestConfig })  
  return res.data
}