/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetNetworkTransferPricesQueryResponse, GetNetworkTransferPricesPathParams } from "../types/GetNetworkTransferPrices.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetNetworkTransferPricesUrl(apiVersion: GetNetworkTransferPricesPathParams["apiVersion"]) {
  const res = { method: 'GET', url: `/${apiVersion}/network-transfer/prices` as const }  
  return res
}

/**
 * @description Returns collection of network transfer prices, including any region-specific rates.<<LB>>---- __CLI__.    ```    linode-cli network-transfer prices    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)
 * @summary List network transfer prices
 * {@link /:apiVersion/network-transfer/prices}
 */
export async function getNetworkTransferPrices(apiVersion: GetNetworkTransferPricesPathParams["apiVersion"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetNetworkTransferPricesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetNetworkTransferPricesUrl(apiVersion).url.toString(), ... requestConfig })  
  return res.data
}