/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/fetch.ts";
import type { GetObjectStorageQuotaUsageQueryResponse, GetObjectStorageQuotaUsagePathParams } from "../types/GetObjectStorageQuotaUsage.ts";
import { fetch } from "../.kubb/fetch.ts";

function getGetObjectStorageQuotaUsageUrl(objQuotaId: GetObjectStorageQuotaUsagePathParams["objQuotaId"]) {
  const res = { method: 'GET', url: `/object-storage/quotas/${objQuotaId}/usage` as const }  
  return res
}

/**
 * @description Returns usage data for a specific `objQuotaId`. This includes the maximum number of `objQuotaId` resources you can have for a single endpoint and the current usage for that resource.<<LB>>---- __CLI__.    ```    linode-cli object-storage quota-usage-view obj-objects-us-ord-1    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    object_storage:read_only    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Get Object Storage quota usage data
 * {@link /object-storage/quotas/:objQuotaId/usage}
 */
export async function getObjectStorageQuotaUsage(objQuotaId: GetObjectStorageQuotaUsagePathParams["objQuotaId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetObjectStorageQuotaUsageQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetObjectStorageQuotaUsageUrl(objQuotaId).url.toString(), ... requestConfig })  
  return res.data
}