/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetObjectStorageBucketAclQueryResponse, GetObjectStorageBucketAclPathParams, GetObjectStorageBucketAclQueryParams } from "../types/GetObjectStorageBucketAcl.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetObjectStorageBucketAclUrl(apiVersion: GetObjectStorageBucketAclPathParams["apiVersion"], regionId: GetObjectStorageBucketAclPathParams["regionId"], bucket: GetObjectStorageBucketAclPathParams["bucket"]) {
  const res = { method: 'GET', url: `/${apiVersion}/object-storage/buckets/${regionId}/${bucket}/object-acl` as const }  
  return res
}

/**
 * @description View a specific object's access control list (ACL) settings. ACLs define who can access your buckets and objects and specify the level of access granted to those users.> 📘>> You can use an outside API, such as the [Ceph Object Gateway S3 API](https://docs.ceph.com/en/latest/radosgw/s3/objectops/#get-object-acl) for more options.<<LB>>---- __OAuth scopes__.    ```    object_storage:read_only    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Get an Object Storage object ACL configuration
 * {@link /:apiVersion/object-storage/buckets/:regionId/:bucket/object-acl}
 */
export async function getObjectStorageBucketAcl(apiVersion: GetObjectStorageBucketAclPathParams["apiVersion"], regionId: GetObjectStorageBucketAclPathParams["regionId"], bucket: GetObjectStorageBucketAclPathParams["bucket"], params: GetObjectStorageBucketAclQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetObjectStorageBucketAclQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetObjectStorageBucketAclUrl(apiVersion, regionId, bucket).url.toString(), params, ... requestConfig })  
  return res.data
}