/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetTransferQueryResponse, GetTransferPathParams } from "../types/GetTransfer.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetTransferUrl(apiVersion: GetTransferPathParams["apiVersion"]) {
  const res = { method: 'GET', url: `/${apiVersion}/account/transfer` as const }  
  return res
}

/**
 * @description Returns a Transfer object showing your network utilization, in GB, for the current month.<<LB>>---- __CLI__.    ```    linode-cli account transfer    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    account:read_only    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Get network usage
 * {@link /:apiVersion/account/transfer}
 */
export async function getTransfer(apiVersion: GetTransferPathParams["apiVersion"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetTransferQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetTransferUrl(apiVersion).url.toString(), ... requestConfig })  
  return res.data
}