/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetVpcsQueryResponse, GetVpcsPathParams, GetVpcsQueryParams } from "../types/GetVpcs.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetVpcsUrl(apiVersion: GetVpcsPathParams["apiVersion"]) {
  const res = { method: 'GET', url: `/${apiVersion}/vpcs` as const }  
  return res
}

/**
 * @description Display all VPCs on your account.<<LB>>---- __CLI__.    ```    linode-cli vpcs list    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)
 * @summary List VPCs
 * {@link /:apiVersion/vpcs}
 */
export async function getVpcs(apiVersion: GetVpcsPathParams["apiVersion"], params?: GetVpcsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetVpcsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetVpcsUrl(apiVersion).url.toString(), params, ... requestConfig })  
  return res.data
}