/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PostTagMutationRequest, PostTagMutationResponse, PostTagPathParams } from "../types/PostTag.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getPostTagUrl(apiVersion: PostTagPathParams["apiVersion"]) {
  const res = { method: 'POST', url: `/${apiVersion}/tags` as const }  
  return res
}

/**
 * @description Creates a new tag and lets you optionally add it to specific objects. Tags are labels you can attach to objects in your account. Use them to specify and group attributes of objects that are relevant to you. Currently, you can add a tag to your `linodes`, your `nodebalancers`, the `domains` for your Linodes, and the `volumes` on your Linodes.> 📘>> - This operation can only be accessed by account users with _unrestricted_ access. Talk to your local account administrator about access management.>> - If you don't add a tag to a supported object with this operation, you can use that object's update operation to later add the tag you created.<<LB>>---- __CLI__.    ```    linode-cli tags create \  --label 'example tag' \  --linodes 123 \  --linodes 456 \  --volumes 9082 \  --volumes 10003    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    account:read_write    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Create a tag
 * {@link /:apiVersion/tags}
 */
export async function postTag(apiVersion: PostTagPathParams["apiVersion"], data: PostTagMutationRequest, config: Partial<RequestConfig<PostTagMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostTagMutationResponse, ResponseErrorConfig<Error>, PostTagMutationRequest>({ method : "POST", url : getPostTagUrl(apiVersion).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}