/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/fetch.ts";
import type { PutAccountMutationRequest, PutAccountMutationResponse } from "../types/PutAccount.ts";
import { fetch } from "../.kubb/fetch.ts";

function getPutAccountUrl() {
  const res = { method: 'PUT', url: `/account` as const }  
  return res
}

/**
 * @description Updates contact and billing information related to your account. If you exclude any properties from the request, the operation leaves them unchanged.> 📘>> When updating an account's `country` to `US`, you'll get an error if the account's `zip` is not a valid US zip code.**Parent and child accounts**In a [parent and child account](https://www.linode.com/docs/guides/parent-child-accounts/) environment, the following apply:- You can't change the `company` for a parent account. Akamai uses this value to set the name for a child account parent user (proxy user) on any child account.- Child account users can't run this operation. These users don't have access to billing-related operations.<<LB>>---- __CLI__.    ```    linode-cli account update \  --address_1 "123 Main St." \  --address_2 "Suite 101" \  --city Philadelphia \  --company My Company \ LLC \  --country US \  --email jsmith@mycompany.com \  --first_name John \  --last_name Smith \  --phone 555-555-1212 \  --state PA \  --tax_id ATU99999999 \  --zip 19102    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    account:read_write    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Update your account
 * {@link /account}
 */
export async function putAccount(data?: PutAccountMutationRequest, config: Partial<RequestConfig<PutAccountMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutAccountMutationResponse, ResponseErrorConfig<Error>, PutAccountMutationRequest>({ method : "PUT", url : getPutAccountUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}