/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/fetch.ts";
import type { PutObjectStorageKeyMutationRequest, PutObjectStorageKeyMutationResponse, PutObjectStorageKeyPathParams } from "../types/PutObjectStorageKey.ts";
import { fetch } from "../.kubb/fetch.ts";

function getPutObjectStorageKeyUrl(keyId: PutObjectStorageKeyPathParams["keyId"]) {
  const res = { method: 'PUT', url: `/object-storage/keys/${keyId}` as const }  
  return res
}

/**
 * @description Updates an Object Storage access key on your account. A successful request triggers an `obj_access_key_update` [event](https://techdocs.akamai.com/linode-api/reference/get-events).> 📘>> This operation has specific [rate limits](https://techdocs.akamai.com/linode-api/reference/rate-limits#specific-operation-rate-limits).<<LB>>---- __CLI__.    ```    linode-cli object-storage keys-update \  --keyId 12345  --label "my-object-storage-key"    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    object_storage:read_write    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Update an Object Storage access key
 * {@link /object-storage/keys/:keyId}
 */
export async function putObjectStorageKey(keyId: PutObjectStorageKeyPathParams["keyId"], data?: PutObjectStorageKeyMutationRequest, config: Partial<RequestConfig<PutObjectStorageKeyMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutObjectStorageKeyMutationResponse, ResponseErrorConfig<Error>, PutObjectStorageKeyMutationRequest>({ method : "PUT", url : getPutObjectStorageKeyUrl(keyId).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}