/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from "../.kubb/fetch.ts";
import type { PutSshKeyMutationRequest, PutSshKeyMutationResponse, PutSshKeyPathParams } from "../types/PutSshKey.ts";
import { fetch } from "../.kubb/fetch.ts";

function getPutSshKeyUrl(sshKeyId: PutSshKeyPathParams["sshKeyId"]) {
  const res = { method: 'PUT', url: `/profile/sshkeys/${sshKeyId}` as const }  
  return res
}

/**
 * @description Updates an SSH Key that you have permission to `read_write`.Only SSH key labels can be updated.<<LB>>---- __CLI__.    ```    linode-cli sshkeys update 42 \  --label "my laptop"    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    account:read_write    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Update an SSH key
 * {@link /profile/sshkeys/:sshKeyId}
 */
export async function putSshKey(sshKeyId: PutSshKeyPathParams["sshKeyId"], data?: PutSshKeyMutationRequest, config: Partial<RequestConfig<PutSshKeyMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutSshKeyMutationResponse, ResponseErrorConfig<Error>, PutSshKeyMutationRequest>({ method : "PUT", url : getPutSshKeyUrl(sshKeyId).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}