/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { DeleteVpcSubnetMutationResponse, DeleteVpcSubnetPathParams } from "../types/DeleteVpcSubnet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getDeleteVpcSubnetUrl(apiVersion: DeleteVpcSubnetPathParams["apiVersion"], vpcId: DeleteVpcSubnetPathParams["vpcId"], vpcSubnetId: DeleteVpcSubnetPathParams["vpcSubnetId"]) {
  const res = { method: 'DELETE', url: `/${apiVersion}/vpcs/${vpcId}/subnets/${vpcSubnetId}` as const }  
  return res
}

/**
 * @description Delete a single VPC subnet.The user accessing this operation must have `read_write` grants to the VPC. A successful request triggers a `subnet_delete` event.> 📘>> You need to delete all the Configuration Profile Interfaces that this subnet is assigned to before you can delete it. If those interfaces are active, the associated Linode needs to be shut down before they can be removed.<<LB>>---- __CLI__.    ```    linode-cli vpcs subnet-delete $vpcId $vpcSubnetId    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    vpc:read_write    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Delete a VPC subnet
 * {@link /:apiVersion/vpcs/:vpcId/subnets/:vpcSubnetId}
 */
export async function deleteVpcSubnet(apiVersion: DeleteVpcSubnetPathParams["apiVersion"], vpcId: DeleteVpcSubnetPathParams["vpcId"], vpcSubnetId: DeleteVpcSubnetPathParams["vpcSubnetId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteVpcSubnetMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteVpcSubnetUrl(apiVersion, vpcId, vpcSubnetId).url.toString(), ... requestConfig })  
  return res.data
}