/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetLinodeFirewallsQueryResponse, GetLinodeFirewallsPathParams, GetLinodeFirewallsQueryParams } from "../types/GetLinodeFirewalls.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetLinodeFirewallsUrl(apiVersion: GetLinodeFirewallsPathParams["apiVersion"], linodeId: GetLinodeFirewallsPathParams["linodeId"]) {
  const res = { method: 'GET', url: `/${apiVersion}/linode/instances/${linodeId}/firewalls` as const }  
  return res
}

/**
 * @description View Firewall information for Firewalls assigned to this Linode.<<LB>>---- __CLI__.    ```    linode-cli linodes firewalls-list 123    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    linodes:read_only    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary List a Linode's firewalls
 * {@link /:apiVersion/linode/instances/:linodeId/firewalls}
 */
export async function getLinodeFirewalls(apiVersion: GetLinodeFirewallsPathParams["apiVersion"], linodeId: GetLinodeFirewallsPathParams["linodeId"], params?: GetLinodeFirewallsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetLinodeFirewallsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetLinodeFirewallsUrl(apiVersion, linodeId).url.toString(), params, ... requestConfig })  
  return res.data
}