/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { GetPaymentMethodQueryResponse, GetPaymentMethodPathParams } from "../types/GetPaymentMethod.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getGetPaymentMethodUrl(apiVersion: GetPaymentMethodPathParams["apiVersion"], paymentMethodId: GetPaymentMethodPathParams["paymentMethodId"]) {
  const res = { method: 'GET', url: `/${apiVersion}/account/payment-methods/${paymentMethodId}` as const }  
  return res
}

/**
 * @description View the details of the specified Payment Method.<<LB>>---- __CLI__.    ```    linode-cli payment-methods view 123    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    account:read_only    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Get a payment method
 * {@link /:apiVersion/account/payment-methods/:paymentMethodId}
 */
export async function getPaymentMethod(apiVersion: GetPaymentMethodPathParams["apiVersion"], paymentMethodId: GetPaymentMethodPathParams["paymentMethodId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetPaymentMethodQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetPaymentMethodUrl(apiVersion, paymentMethodId).url.toString(), ... requestConfig })  
  return res.data
}