/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PostManagedServiceMutationRequest, PostManagedServiceMutationResponse, PostManagedServicePathParams } from "../types/PostManagedService.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getPostManagedServiceUrl(apiVersion: PostManagedServicePathParams["apiVersion"]) {
  const res = { method: 'POST', url: `/${apiVersion}/managed/services` as const }  
  return res
}

/**
 * @description Creates a service monitor. Linode Managed monitors this service and alerts Akamai Support when issues are detected.This operation can only be accessed by the unrestricted users of an account.<<LB>>---- __CLI__.    ```    linode-cli managed service-create \  --service_type url \  --label prod-1 \  --address "https://example.org" \  --timeout 30 \  --body "it worked" \  --consultation_group on-call \  --notes "The service name is \    my-cool-application" \  --credentials 9991    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    account:read_write    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Create a managed service
 * {@link /:apiVersion/managed/services}
 */
export async function postManagedService(apiVersion: PostManagedServicePathParams["apiVersion"], data: PostManagedServiceMutationRequest, config: Partial<RequestConfig<PostManagedServiceMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostManagedServiceMutationResponse, ResponseErrorConfig<Error>, PostManagedServiceMutationRequest>({ method : "POST", url : getPostManagedServiceUrl(apiVersion).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}