/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PostLkeClusterMutationRequest, PostLkeClusterMutationResponse, PostLkeClusterPathParams } from "../types/PostLkeCluster.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getPostLkeClusterUrl(apiVersion: PostLkeClusterPathParams["apiVersion"]) {
  const res = { method: 'POST', url: `/${apiVersion}/lke/clusters` as const }  
  return res
}

/**
 * @description Creates a Kubernetes cluster. The Kubernetes cluster will be created asynchronously. You can use the events system to determine when the Kubernetes cluster is ready to use. Please note that it often takes 2-5 minutes before the [Kubernetes API endpoints](https://techdocs.akamai.com/linode-api/reference/get-lke-cluster-api-endpoints) and the [Kubeconfig file](https://techdocs.akamai.com/linode-api/reference/get-lke-cluster-kubeconfig) for the new cluster are ready.<<LB>>---- __CLI__.    ```    linode-cli lke cluster-create \  --label cluster12345 \  --region us-central \  --k8s_version 1.33 \  --apl_enabled false \  --control_plane.high_availability true \  --node_pools.type g6-standard-4 --node_pools.count 6 \  --node_pools.type g6-standard-8 --node_pools.count 3 \  --node_pools.autoscaler.enabled true \  --node_pools.autoscaler.max 12 \  --node_pools.autoscaler.min 3 \  --tags ecomm    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    lke:read_write    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Create a Kubernetes cluster
 * {@link /:apiVersion/lke/clusters}
 */
export async function postLkeCluster(apiVersion: PostLkeClusterPathParams["apiVersion"], data: PostLkeClusterMutationRequest, config: Partial<RequestConfig<PostLkeClusterMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostLkeClusterMutationResponse, ResponseErrorConfig<Error>, PostLkeClusterMutationRequest>({ method : "POST", url : getPostLkeClusterUrl(apiVersion).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}