/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PostTicketReplyMutationRequest, PostTicketReplyMutationResponse, PostTicketReplyPathParams } from "../types/PostTicketReply.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getPostTicketReplyUrl(apiVersion: PostTicketReplyPathParams["apiVersion"], ticketId: PostTicketReplyPathParams["ticketId"]) {
  const res = { method: 'POST', url: `/${apiVersion}/support/tickets/${ticketId}/replies` as const }  
  return res
}

/**
 * @description Adds a reply to an existing support ticket.<<LB>>---- __CLI__.    ```    linode-cli tickets reply 11223344 \  --description "Thank you for your help. I was able to figure out what the problem was and I successfully reset my password. You guys are the best!"    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    account:read_write    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Create a reply
 * {@link /:apiVersion/support/tickets/:ticketId/replies}
 */
export async function postTicketReply(apiVersion: PostTicketReplyPathParams["apiVersion"], ticketId: PostTicketReplyPathParams["ticketId"], data: PostTicketReplyMutationRequest, config: Partial<RequestConfig<PostTicketReplyMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PostTicketReplyMutationResponse, ResponseErrorConfig<Error>, PostTicketReplyMutationRequest>({ method : "POST", url : getPostTicketReplyUrl(apiVersion, ticketId).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}