/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PostDatabasesPostgreSqlInstanceCredentialsResetMutationResponse, PostDatabasesPostgreSqlInstanceCredentialsResetPathParams } from "../types/PostDatabasesPostgreSqlInstanceCredentialsReset.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getPostDatabasesPostgreSqlInstanceCredentialsResetUrl(apiVersion: PostDatabasesPostgreSqlInstanceCredentialsResetPathParams["apiVersion"], instanceId: PostDatabasesPostgreSqlInstanceCredentialsResetPathParams["instanceId"]) {
  const res = { method: 'POST', url: `/${apiVersion}/databases/postgresql/instances/${instanceId}/credentials/reset` as const }  
  return res
}

/**
 * @description Reset the root password for a PostgreSQL Managed Database. A new root password is randomly generated and accessible with the [Get PostgreSQL Managed Database credentials](https://techdocs.akamai.com/linode-api/reference/get-databases-postgre-sql-instance-credentials) operation.- The database's status needs to be `active`.- Only unrestricted users can access this operation. These users have access regardless of the acting token's OAuth scopes.- It may take several seconds for credentials to reset.<<LB>>---- __CLI__.    ```    linode-cli databases postgresql-creds-reset 123    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    databases:read_write    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Reset PostgreSQL Managed Database credentials
 * {@link /:apiVersion/databases/postgresql/instances/:instanceId/credentials/reset}
 */
export async function postDatabasesPostgreSqlInstanceCredentialsReset(apiVersion: PostDatabasesPostgreSqlInstanceCredentialsResetPathParams["apiVersion"], instanceId: PostDatabasesPostgreSqlInstanceCredentialsResetPathParams["instanceId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<PostDatabasesPostgreSqlInstanceCredentialsResetMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getPostDatabasesPostgreSqlInstanceCredentialsResetUrl(apiVersion, instanceId).url.toString(), ... requestConfig })  
  return res.data
}