/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/fetch";
import type { PutDomainRecordMutationRequest, PutDomainRecordMutationResponse, PutDomainRecordPathParams } from "../types/PutDomainRecord.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/fetch";

function getPutDomainRecordUrl(apiVersion: PutDomainRecordPathParams["apiVersion"], domainId: PutDomainRecordPathParams["domainId"], recordId: PutDomainRecordPathParams["recordId"]) {
  const res = { method: 'PUT', url: `/${apiVersion}/domains/${domainId}/records/${recordId}` as const }  
  return res
}

/**
 * @description Updates a single Record on this Domain.<<LB>>---- __CLI__.    ```    linode-cli domains records-update 123 234 \  --name test \  --target 203.0.113.1 \  --priority 50 \  --weight 50 \  --port 80 \  --ttl_sec 604800    ```    [Learn more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)- __OAuth scopes__.    ```    domains:read_write    ```    [Learn more...](https://techdocs.akamai.com/linode-api/reference/get-started#oauth)
 * @summary Update a domain record
 * {@link /:apiVersion/domains/:domainId/records/:recordId}
 */
export async function putDomainRecord(apiVersion: PutDomainRecordPathParams["apiVersion"], domainId: PutDomainRecordPathParams["domainId"], recordId: PutDomainRecordPathParams["recordId"], data?: PutDomainRecordMutationRequest, config: Partial<RequestConfig<PutDomainRecordMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PutDomainRecordMutationResponse, ResponseErrorConfig<Error>, PutDomainRecordMutationRequest>({ method : "PUT", url : getPutDomainRecordUrl(apiVersion, domainId, recordId).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}